// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

import (
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/client"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/operations"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

var createCmdMeta = []flagutil.FlagMeta{
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional. The user-provided name of the webhook."},
	{FlagName: "subscribed-event", Shorthand: "s", FieldPath: "Body.SubscribedEvent", Kind: flagutil.FlagKindStringArray, Required: true, Description: "Required. The events that the webhook is subscribed to.\nAvailable events:\n- batch.succeeded\n- batch.expired\n- batch.failed\n- interaction.requires_action\n- interaction.completed\n- interaction.failed\n- video.generated [required]"},
	{FlagName: "uri", Shorthand: "u", FieldPath: "Body.URI", Kind: flagutil.FlagKindString, Required: true, Description: "Required. The URI to which webhook events will be sent. [required]"},
}

// initCreateCmd initializes the create command.
func initCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create a webhook endpoint",
		Long:    "Creates a new Webhook.",
		Example: "  gemini-api webhooks create --subscribed-event batch.succeeded --subscribed-event batch.failed --uri https://my-api.com/gemini-callback",
		Args:    cobra.NoArgs,
		RunE:    runCreateCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "CreateWebhook",
		},
	}
	flagutil.RegisterFlags(cmd, createCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateWebhookRequest](createCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, createCmdMeta, "Body", "body"); err != nil {
		return fmt.Errorf("annotate body fields for create: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runCreateCmd executes the create command.
func runCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "CreateWebhook")
	}
	req, err := flagutil.BuildRequest[operations.CreateWebhookRequest](cmd, createCmdMeta, "Body", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Webhooks.Create(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
