// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

import (
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/client"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/operations"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

var pingCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Required. The ID of the webhook to ping. [required]"},
	{FlagName: "body-param", Shorthand: "b", FieldPath: "Body", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `request:"mediaType=application/json"`, Description: "Required. The request body."},
}

// initPingCmd initializes the ping command.
func initPingCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "ping",
		Short:   "Send a ping event to a webhook",
		Long:    "Sends a ping event to a Webhook.",
		Example: "",
		Args:    cobra.NoArgs,
		RunE:    runPingCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "PingWebhook",
		},
	}
	flagutil.RegisterFlags(cmd, pingCmdMeta)
	if err := flagutil.ValidateMeta[operations.PingWebhookRequest](pingCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for ping: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, pingCmdMeta, "Body", "body"); err != nil {
		return fmt.Errorf("annotate body fields for ping: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runPingCmd executes the ping command.
func runPingCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "PingWebhook")
	}
	req, err := flagutil.BuildRequest[operations.PingWebhookRequest](cmd, pingCmdMeta, "Body", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Webhooks.Ping(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
