// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/interactions"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type CancelInteractionByIDGlobals struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
}

func (c CancelInteractionByIDGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CancelInteractionByIDGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CancelInteractionByIDGlobals) GetAPIVersion() *string {
	if c == nil {
		return nil
	}
	return c.APIVersion
}

func (c *CancelInteractionByIDGlobals) GetAPIRevision() *string {
	if c == nil {
		return nil
	}
	return c.APIRevision
}

type CancelInteractionByIDRequest struct {
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Required. The name of the interaction to cancel.
	ID string `pathParam:"style=simple,explode=false,name=interactionsId"`
}

func (c CancelInteractionByIDRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CancelInteractionByIDRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CancelInteractionByIDRequest) GetAPIRevision() *string {
	if c == nil {
		return nil
	}
	return c.APIRevision
}

func (c *CancelInteractionByIDRequest) GetAPIVersion() *string {
	if c == nil {
		return nil
	}
	return c.APIVersion
}

func (c *CancelInteractionByIDRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type CancelInteractionByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	Interaction *interactions.Interaction
}

func (c CancelInteractionByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CancelInteractionByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CancelInteractionByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CancelInteractionByIDResponse) GetInteraction() *interactions.Interaction {
	if c == nil {
		return nil
	}
	return c.Interaction
}
