// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/agents"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type CreateAgentGlobals struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
}

func (c CreateAgentGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAgentGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAgentGlobals) GetAPIVersion() *string {
	if c == nil {
		return nil
	}
	return c.APIVersion
}

func (c *CreateAgentGlobals) GetAPIRevision() *string {
	if c == nil {
		return nil
	}
	return c.APIRevision
}

type CreateAgentRequest struct {
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// The request body.
	Body agents.Agent `request:"mediaType=application/json"`
}

func (c CreateAgentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAgentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAgentRequest) GetAPIRevision() *string {
	if c == nil {
		return nil
	}
	return c.APIRevision
}

func (c *CreateAgentRequest) GetAPIVersion() *string {
	if c == nil {
		return nil
	}
	return c.APIVersion
}

func (c *CreateAgentRequest) GetBody() agents.Agent {
	if c == nil {
		return agents.Agent{}
	}
	return c.Body
}

type CreateAgentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	Agent *agents.Agent
}

func (c CreateAgentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAgentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAgentResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateAgentResponse) GetAgent() *agents.Agent {
	if c == nil {
		return nil
	}
	return c.Agent
}
