// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/credentials"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type CreateCredentialGlobals struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
}

func (c CreateCredentialGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCredentialGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCredentialGlobals) GetAPIVersion() *string {
	if c == nil {
		return nil
	}
	return c.APIVersion
}

type CreateCredentialRequest struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string                            `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	Body       credentials.CredentialCreateParams `request:"mediaType=application/json"`
}

func (c CreateCredentialRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCredentialRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCredentialRequest) GetAPIVersion() *string {
	if c == nil {
		return nil
	}
	return c.APIVersion
}

func (c *CreateCredentialRequest) GetBody() credentials.CredentialCreateParams {
	if c == nil {
		return credentials.CredentialCreateParams{}
	}
	return c.Body
}

func (c *CreateCredentialRequest) GetBodyEnvironmentVariable() *credentials.EnvironmentVariableConfig {
	return c.GetBody().EnvironmentVariableConfig
}

func (c *CreateCredentialRequest) GetBodyBearerToken() *credentials.HTTPBearerConfig {
	return c.GetBody().HTTPBearerConfig
}

func (c *CreateCredentialRequest) GetBodyOauth2() *credentials.OAuth2Config {
	return c.GetBody().OAuth2Config
}

type CreateCredentialResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	Credential *credentials.Credential
}

func (c CreateCredentialResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCredentialResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCredentialResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCredentialResponse) GetCredential() *credentials.Credential {
	if c == nil {
		return nil
	}
	return c.Credential
}
