// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/interactions"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type DeleteWebhookGlobals struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
}

func (d DeleteWebhookGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteWebhookGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteWebhookGlobals) GetAPIVersion() *string {
	if d == nil {
		return nil
	}
	return d.APIVersion
}

func (d *DeleteWebhookGlobals) GetAPIRevision() *string {
	if d == nil {
		return nil
	}
	return d.APIRevision
}

type DeleteWebhookRequest struct {
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Required. The ID of the webhook to delete.
	// Format: `{webhook_id}`
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d DeleteWebhookRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteWebhookRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteWebhookRequest) GetAPIRevision() *string {
	if d == nil {
		return nil
	}
	return d.APIRevision
}

func (d *DeleteWebhookRequest) GetAPIVersion() *string {
	if d == nil {
		return nil
	}
	return d.APIVersion
}

func (d *DeleteWebhookRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	Empty *interactions.Empty
}

func (d DeleteWebhookResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteWebhookResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteWebhookResponse) GetEmpty() *interactions.Empty {
	if d == nil {
		return nil
	}
	return d.Empty
}
