// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/genai"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type FilesGetGlobals struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
}

func (f FilesGetGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilesGetGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FilesGetGlobals) GetAPIVersion() *string {
	if f == nil {
		return nil
	}
	return f.APIVersion
}

type FilesGetRequest struct {
	// Which version of the API to use. Defaults to v1beta.
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// File to get, as files/<id> or a bare id (also accepted as an argument)
	File string `pathParam:"style=simple,explode=false,name=file"`
}

func (f FilesGetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilesGetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FilesGetRequest) GetAPIVersion() *string {
	if f == nil {
		return nil
	}
	return f.APIVersion
}

func (f *FilesGetRequest) GetFile() string {
	if f == nil {
		return ""
	}
	return f.File
}

type FilesGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	File *genai.File
}

func (f FilesGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilesGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FilesGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FilesGetResponse) GetFile() *genai.File {
	if f == nil {
		return nil
	}
	return f.File
}
