// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/genai"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type FilesRegisterGlobals struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
}

func (f FilesRegisterGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilesRegisterGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FilesRegisterGlobals) GetAPIVersion() *string {
	if f == nil {
		return nil
	}
	return f.APIVersion
}

type FilesRegisterRequest struct {
	// Which version of the API to use. Defaults to v1beta.
	APIVersion *string                    `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	Body       genai.RegisterFilesRequest `request:"mediaType=application/json"`
}

func (f FilesRegisterRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilesRegisterRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FilesRegisterRequest) GetAPIVersion() *string {
	if f == nil {
		return nil
	}
	return f.APIVersion
}

func (f *FilesRegisterRequest) GetBody() genai.RegisterFilesRequest {
	if f == nil {
		return genai.RegisterFilesRequest{}
	}
	return f.Body
}

type FilesRegisterResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	RegisterFilesResponse *genai.RegisterFilesResponse
}

func (f FilesRegisterResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilesRegisterResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FilesRegisterResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FilesRegisterResponse) GetRegisterFilesResponse() *genai.RegisterFilesResponse {
	if f == nil {
		return nil
	}
	return f.RegisterFilesResponse
}
