// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/genai"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type FilesListGlobals struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
}

func (f FilesListGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilesListGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FilesListGlobals) GetAPIVersion() *string {
	if f == nil {
		return nil
	}
	return f.APIVersion
}

type FilesListRequest struct {
	// Which version of the API to use. Defaults to v1beta.
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Optional. Maximum number of `File`s to return per page. If unspecified, defaults to 10. Maximum `page_size` is 100.
	PageSize *int `queryParam:"style=form,explode=true,name=pageSize"`
	// Optional. A page token from a previous `ListFiles` call.
	PageToken *string `queryParam:"style=form,explode=true,name=pageToken"`
}

func (f FilesListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilesListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FilesListRequest) GetAPIVersion() *string {
	if f == nil {
		return nil
	}
	return f.APIVersion
}

func (f *FilesListRequest) GetPageSize() *int {
	if f == nil {
		return nil
	}
	return f.PageSize
}

func (f *FilesListRequest) GetPageToken() *string {
	if f == nil {
		return nil
	}
	return f.PageToken
}

type FilesListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	ListFilesResponse *genai.ListFilesResponse

	Next func() (*FilesListResponse, error)
}

func (f FilesListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilesListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FilesListResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FilesListResponse) GetListFilesResponse() *genai.ListFilesResponse {
	if f == nil {
		return nil
	}
	return f.ListFilesResponse
}
