// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/triggers"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type GetTriggerGlobals struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
}

func (g GetTriggerGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTriggerGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTriggerGlobals) GetAPIVersion() *string {
	if g == nil {
		return nil
	}
	return g.APIVersion
}

func (g *GetTriggerGlobals) GetAPIRevision() *string {
	if g == nil {
		return nil
	}
	return g.APIRevision
}

type GetTriggerRequest struct {
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Resource name of the trigger.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g GetTriggerRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTriggerRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTriggerRequest) GetAPIRevision() *string {
	if g == nil {
		return nil
	}
	return g.APIRevision
}

func (g *GetTriggerRequest) GetAPIVersion() *string {
	if g == nil {
		return nil
	}
	return g.APIVersion
}

func (g *GetTriggerRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetTriggerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	Trigger *triggers.Trigger
}

func (g GetTriggerResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTriggerResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTriggerResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTriggerResponse) GetTrigger() *triggers.Trigger {
	if g == nil {
		return nil
	}
	return g.Trigger
}
