// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/triggers"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type ListTriggerExecutionsGlobals struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
}

func (l ListTriggerExecutionsGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTriggerExecutionsGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListTriggerExecutionsGlobals) GetAPIVersion() *string {
	if l == nil {
		return nil
	}
	return l.APIVersion
}

func (l *ListTriggerExecutionsGlobals) GetAPIRevision() *string {
	if l == nil {
		return nil
	}
	return l.APIRevision
}

type ListTriggerExecutionsRequest struct {
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Resource name of the trigger.
	TriggerID string `pathParam:"style=simple,explode=false,name=trigger_id"`
	// Optional. The maximum number of executions to return per page.
	PageSize *int64 `queryParam:"style=form,explode=true,name=page_size"`
	// Optional. A page token from a previous ListTriggerExecutions call.
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
}

func (l ListTriggerExecutionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTriggerExecutionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListTriggerExecutionsRequest) GetAPIRevision() *string {
	if l == nil {
		return nil
	}
	return l.APIRevision
}

func (l *ListTriggerExecutionsRequest) GetAPIVersion() *string {
	if l == nil {
		return nil
	}
	return l.APIVersion
}

func (l *ListTriggerExecutionsRequest) GetTriggerID() string {
	if l == nil {
		return ""
	}
	return l.TriggerID
}

func (l *ListTriggerExecutionsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListTriggerExecutionsRequest) GetPageToken() *string {
	if l == nil {
		return nil
	}
	return l.PageToken
}

type ListTriggerExecutionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	ListTriggerExecutionsResponse *triggers.ListTriggerExecutionsResponse

	Next func() (*ListTriggerExecutionsResponse, error)
}

func (l ListTriggerExecutionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTriggerExecutionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListTriggerExecutionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListTriggerExecutionsResponse) GetListTriggerExecutionsResponse() *triggers.ListTriggerExecutionsResponse {
	if l == nil {
		return nil
	}
	return l.ListTriggerExecutionsResponse
}
