// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/credentials"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type ListCredentialsGlobals struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
}

func (l ListCredentialsGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCredentialsGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCredentialsGlobals) GetAPIVersion() *string {
	if l == nil {
		return nil
	}
	return l.APIVersion
}

type ListCredentialsRequest struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Optional. Maximum number of credentials to return.
	// If unspecified, defaults to 50. Maximum is 1000.
	PageSize *int `queryParam:"style=form,explode=true,name=page_size"`
	// Optional. Pagination token.
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
}

func (l ListCredentialsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCredentialsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCredentialsRequest) GetAPIVersion() *string {
	if l == nil {
		return nil
	}
	return l.APIVersion
}

func (l *ListCredentialsRequest) GetPageSize() *int {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListCredentialsRequest) GetPageToken() *string {
	if l == nil {
		return nil
	}
	return l.PageToken
}

type ListCredentialsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	CredentialListResponse *credentials.CredentialListResponse
}

func (l ListCredentialsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCredentialsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCredentialsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListCredentialsResponse) GetCredentialListResponse() *credentials.CredentialListResponse {
	if l == nil {
		return nil
	}
	return l.CredentialListResponse
}
