// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/agents"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type ListAgentsGlobals struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
}

func (l ListAgentsGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAgentsGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAgentsGlobals) GetAPIVersion() *string {
	if l == nil {
		return nil
	}
	return l.APIVersion
}

func (l *ListAgentsGlobals) GetAPIRevision() *string {
	if l == nil {
		return nil
	}
	return l.APIRevision
}

type ListAgentsRequest struct {
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	PageSize   *int    `queryParam:"style=form,explode=true,name=page_size"`
	PageToken  *string `queryParam:"style=form,explode=true,name=page_token"`
	// Required. The parent resource to list agents from.
	// Format: `projects/{project}/locations/{location}`
	Parent *string `queryParam:"style=form,explode=true,name=parent"`
}

func (l ListAgentsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAgentsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAgentsRequest) GetAPIRevision() *string {
	if l == nil {
		return nil
	}
	return l.APIRevision
}

func (l *ListAgentsRequest) GetAPIVersion() *string {
	if l == nil {
		return nil
	}
	return l.APIVersion
}

func (l *ListAgentsRequest) GetPageSize() *int {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListAgentsRequest) GetPageToken() *string {
	if l == nil {
		return nil
	}
	return l.PageToken
}

func (l *ListAgentsRequest) GetParent() *string {
	if l == nil {
		return nil
	}
	return l.Parent
}

type ListAgentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	AgentListResponse *agents.AgentListResponse

	Next func() (*ListAgentsResponse, error)
}

func (l ListAgentsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAgentsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAgentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAgentsResponse) GetAgentListResponse() *agents.AgentListResponse {
	if l == nil {
		return nil
	}
	return l.AgentListResponse
}
