// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/webhooks"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type RotateSigningSecretGlobals struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
}

func (r RotateSigningSecretGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RotateSigningSecretGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RotateSigningSecretGlobals) GetAPIVersion() *string {
	if r == nil {
		return nil
	}
	return r.APIVersion
}

func (r *RotateSigningSecretGlobals) GetAPIRevision() *string {
	if r == nil {
		return nil
	}
	return r.APIRevision
}

type RotateSigningSecretRequest struct {
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Required. The ID of the webhook for which to generate a signing secret.
	// Format: `{webhook_id}`
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The request body.
	Body *webhooks.RotateSigningSecretRequest `request:"mediaType=application/json"`
}

func (r RotateSigningSecretRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RotateSigningSecretRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RotateSigningSecretRequest) GetAPIRevision() *string {
	if r == nil {
		return nil
	}
	return r.APIRevision
}

func (r *RotateSigningSecretRequest) GetAPIVersion() *string {
	if r == nil {
		return nil
	}
	return r.APIVersion
}

func (r *RotateSigningSecretRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RotateSigningSecretRequest) GetBody() *webhooks.RotateSigningSecretRequest {
	if r == nil {
		return nil
	}
	return r.Body
}

type RotateSigningSecretResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	WebhookRotateSigningSecretResponse *webhooks.WebhookRotateSigningSecretResponse
}

func (r RotateSigningSecretResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RotateSigningSecretResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RotateSigningSecretResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RotateSigningSecretResponse) GetWebhookRotateSigningSecretResponse() *webhooks.WebhookRotateSigningSecretResponse {
	if r == nil {
		return nil
	}
	return r.WebhookRotateSigningSecretResponse
}
