// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/webhooks"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type UpdateWebhookGlobals struct {
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
}

func (u UpdateWebhookGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateWebhookGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateWebhookGlobals) GetAPIVersion() *string {
	if u == nil {
		return nil
	}
	return u.APIVersion
}

func (u *UpdateWebhookGlobals) GetAPIRevision() *string {
	if u == nil {
		return nil
	}
	return u.APIRevision
}

type UpdateWebhookRequest struct {
	// Interactions API revision to request. Omitted by default (matching the official SDKs), so the service serves its current revision.
	APIRevision *string `header:"style=simple,explode=false,name=Api-Revision"`
	// Which version of the API to use. Defaults to v1beta (the only version covering the full interactions surface).
	APIVersion *string `default:"v1beta" pathParam:"style=simple,explode=false,name=api_version"`
	// Required. The ID of the webhook to update.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Optional list of fields to update.
	UpdateMask *string `queryParam:"style=form,explode=true,name=update_mask"`
	// Required. The request body.
	Body *webhooks.WebhookUpdate `request:"mediaType=application/json"`
}

func (u UpdateWebhookRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateWebhookRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateWebhookRequest) GetAPIRevision() *string {
	if u == nil {
		return nil
	}
	return u.APIRevision
}

func (u *UpdateWebhookRequest) GetAPIVersion() *string {
	if u == nil {
		return nil
	}
	return u.APIVersion
}

func (u *UpdateWebhookRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateWebhookRequest) GetUpdateMask() *string {
	if u == nil {
		return nil
	}
	return u.UpdateMask
}

func (u *UpdateWebhookRequest) GetBody() *webhooks.WebhookUpdate {
	if u == nil {
		return nil
	}
	return u.Body
}

type UpdateWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	Webhook *webhooks.Webhook
}

func (u UpdateWebhookResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateWebhookResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateWebhookResponse) GetWebhook() *webhooks.Webhook {
	if u == nil {
		return nil
	}
	return u.Webhook
}
