// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdk

// Generated from OpenAPI doc version v1beta and generator version internal

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/retry"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/config"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/globals"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/hooks"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	// Global Endpoint
	"https://generativelanguage.googleapis.com",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// GeminiAPI - Gemini API: Use the Gemini Interactions API and managed-agent platform from the command line.
//
// Get started:
//
//	Set GEMINI_API_KEY, or run: gemini-api configure
//	Then run a model or managed agent: gemini-api agent --help
//	Add --dry-run to preview any API call without sending it.
type GeminiAPI struct {
	SDKVersion string
	// Run interactions with Gemini models or managed agents, and manage agent definitions.
	//
	// Start here:
	//   gemini-api agent run --help
	//
	// Other common flows:
	//   gemini-api agent create --help   Define a managed agent
	//   gemini-api agent status --help   Inspect a background interaction
	//
	// Note: agent IDs and interaction IDs are distinct resources. "agent status"
	// takes an interaction ID; to inspect an agent definition use "agent get".
	Agent       *Agent
	Credentials *Credentials
	// Manage sandbox environments and inspect environment files
	Environments *Environments
	// Upload, list, inspect, register, and delete files (48-hour retention)
	Files *Files
	// Show the curated offline model catalog; list/get query the live API
	Models *Models
	// Schedule and manage cron triggers that run managed agents
	Triggers *Triggers
	// Manage webhook endpoints and signing secrets for event delivery
	Webhooks *Webhooks

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*GeminiAPI)

// WithServerURL allows providing an alternative server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *GeminiAPI) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *GeminiAPI) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *GeminiAPI) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *GeminiAPI) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(security components.Security) SDKOption {
	return func(sdk *GeminiAPI) {
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *GeminiAPI) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

// WithAPIVersion allows setting the APIVersion parameter for all supported operations
func WithAPIVersion(apiVersion string) SDKOption {
	return func(sdk *GeminiAPI) {
		sdk.sdkConfiguration.Globals.APIVersion = &apiVersion
	}
}

// WithAPIRevision allows setting the APIRevision parameter for all supported operations
func WithAPIRevision(apiRevision string) SDKOption {
	return func(sdk *GeminiAPI) {
		sdk.sdkConfiguration.Globals.APIRevision = &apiRevision
	}
}

// WithUserProject allows setting the UserProject parameter for all supported operations
func WithUserProject(userProject string) SDKOption {
	return func(sdk *GeminiAPI) {
		sdk.sdkConfiguration.Globals.UserProject = &userProject
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *GeminiAPI) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *GeminiAPI) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *GeminiAPI {
	sdk := &GeminiAPI{
		SDKVersion: "0.6.0",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:         "speakeasy-sdk/go 0.6.0 internal v1beta google3/third_party/gemini_api_cli/internal/sdk",
			SDKVersion:        "0.6.0",
			GenVersion:        "internal",
			OpenAPIDocVersion: "v1beta",
			Globals:           globals.Globals{},
			ServerList:        ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.Agent = newAgent(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Credentials = newCredentials(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Environments = newEnvironments(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Files = newFiles(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Models = newModels(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Triggers = newTriggers(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Webhooks = newWebhooks(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
