// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package internal

import (
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/client"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/operations"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

var startUploadCmdMeta = []flagutil.FlagMeta{
	{FlagName: "environment", FieldPath: "Environment", Kind: flagutil.FlagKindString, Required: true, Description: "The ID of the environment that owns the destination file. [required]"},
	{FlagName: "path", Shorthand: "p", FieldPath: "Path", Kind: flagutil.FlagKindString, Required: true, Description: "The relative destination path inside the environment workspace. [required]"},
	{FlagName: "extract", FieldPath: "Extract", Kind: flagutil.FlagKindBool, Optional: true, Description: "Optional. If true, treats the uploaded file as a tar/tar.gz archive and unpacks it into `path`."},
	{FlagName: "overwrite", FieldPath: "Overwrite", Kind: flagutil.FlagKindBool, Optional: true, Description: "Optional. Whether to overwrite the destination file if it already exists."},
	{FlagName: "x-goog-upload-header-content-length", FieldPath: "XGoogUploadHeaderContentLength", Kind: flagutil.FlagKindInt64, Required: true, HasMinimum: true, Minimum: 0, Description: "Total number of file bytes that will be uploaded to the session URL. [required]"},
	{FlagName: "x-goog-upload-header-content-type", FieldPath: "XGoogUploadHeaderContentType", Kind: flagutil.FlagKindString, Required: true, MinLength: 1, Description: "MIME type of the file that will be uploaded to the session URL. [required]"},
}

// initStartUploadCmd initializes the start-upload command.
func initStartUploadCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "start-upload",
		Short:   "Start an environment file upload",
		Long:    "Starts a resumable upload session for a file in an environment workspace.\nUpload the file bytes to the URL returned in the `X-Goog-Upload-URL`\nresponse header, using the resumable upload protocol.",
		Example: "",
		Args:    cobra.NoArgs,
		RunE:    runStartUploadCmd,
		Aliases: []string{"su"},
		Annotations: map[string]string{
			"speakeasy_operation": "StartEnvironmentFileUpload",
		},
	}
	flagutil.RegisterFlags(cmd, startUploadCmdMeta)
	if err := flagutil.ValidateMeta[operations.StartEnvironmentFileUploadRequest](startUploadCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for start-upload: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runStartUploadCmd executes the start-upload command.
func runStartUploadCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.StartEnvironmentFileUploadRequest](cmd, startUploadCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Environments.Internal.StartUpload(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
