// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package genai

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

// ListGeneratedFilesResponse - Response for `ListGeneratedFiles`.
type ListGeneratedFilesResponse struct {
	// The list of `GeneratedFile`s.
	GeneratedFiles []GeneratedFile `json:"generatedFiles,omitzero"`
	// A token that can be sent as a `page_token` into a subsequent `ListGeneratedFiles` call.
	NextPageToken *string `json:"nextPageToken,omitzero"`
}

func (l ListGeneratedFilesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListGeneratedFilesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListGeneratedFilesResponse) GetGeneratedFiles() []GeneratedFile {
	if l == nil {
		return nil
	}
	return l.GeneratedFiles
}

func (l *ListGeneratedFilesResponse) GetNextPageToken() *string {
	if l == nil {
		return nil
	}
	return l.NextPageToken
}
