// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package genai

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

// ListModelsResponse - Response from `ListModel` containing a paginated list of Models.
type ListModelsResponse struct {
	// The returned Models.
	Models []Model `json:"models,omitzero"`
	// A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no more pages.
	NextPageToken *string `json:"nextPageToken,omitzero"`
}

func (l ListModelsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListModelsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListModelsResponse) GetModels() []Model {
	if l == nil {
		return nil
	}
	return l.Models
}

func (l *ListModelsResponse) GetNextPageToken() *string {
	if l == nil {
		return nil
	}
	return l.NextPageToken
}
