// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package genai

import (
	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

// Model - Information about a Generative Language Model.
type Model struct {
	// Required. The name of the base model, pass this to the generation request. Examples: * `gemini-1.5-flash`
	BaseModelID *string `json:"baseModelId,omitzero"`
	// A short description of the model.
	Description *string `json:"description,omitzero"`
	// The human-readable name of the model. E.g. "Gemini 1.5 Flash". The name can be up to 128 characters long and can consist of any UTF-8 characters.
	DisplayName *string `json:"displayName,omitzero"`
	// Maximum number of input tokens allowed for this model.
	InputTokenLimit *int `json:"inputTokenLimit,omitzero"`
	// The maximum temperature this model can use.
	MaxTemperature *float32 `json:"maxTemperature,omitzero"`
	// Required. The resource name of the `Model`. Refer to [Model variants](https://ai.google.dev/gemini-api/docs/models/gemini#model-variations) for all allowed values. Format: `models/{model}` with a `{model}` naming convention of: * "{base_model_id}-{version}" Examples: * `models/gemini-1.5-flash-001`
	Name *string `json:"name,omitzero"`
	// Maximum number of output tokens available for this model.
	OutputTokenLimit *int `json:"outputTokenLimit,omitzero"`
	// The model's supported generation methods. The corresponding API method names are defined as Pascal case strings, such as `generateMessage` and `generateContent`.
	SupportedGenerationMethods []string `json:"supportedGenerationMethods,omitzero"`
	// Controls the randomness of the output. Values can range over `[0.0,max_temperature]`, inclusive. A higher value will produce responses that are more varied, while a value closer to `0.0` will typically result in less surprising responses from the model. This value specifies default to be used by the backend while making the call to the model.
	Temperature *float32 `json:"temperature,omitzero"`
	// Whether the model supports thinking.
	Thinking *bool `json:"thinking,omitzero"`
	// For Top-k sampling. Top-k sampling considers the set of `top_k` most probable tokens. This value specifies default to be used by the backend while making the call to the model. If empty, indicates the model doesn't use top-k sampling, and `top_k` isn't allowed as a generation parameter.
	TopK *int `json:"topK,omitzero"`
	// For [Nucleus sampling](https://ai.google.dev/gemini-api/docs/prompting-strategies#top-p). Nucleus sampling considers the smallest set of tokens whose probability sum is at least `top_p`. This value specifies default to be used by the backend while making the call to the model.
	TopP *float32 `json:"topP,omitzero"`
	// Required. The version number of the model. This represents the major version (`1.0` or `1.5`)
	Version *string `json:"version,omitzero"`
}

func (m Model) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Model) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *Model) GetBaseModelID() *string {
	if m == nil {
		return nil
	}
	return m.BaseModelID
}

func (m *Model) GetDescription() *string {
	if m == nil {
		return nil
	}
	return m.Description
}

func (m *Model) GetDisplayName() *string {
	if m == nil {
		return nil
	}
	return m.DisplayName
}

func (m *Model) GetInputTokenLimit() *int {
	if m == nil {
		return nil
	}
	return m.InputTokenLimit
}

func (m *Model) GetMaxTemperature() *float32 {
	if m == nil {
		return nil
	}
	return m.MaxTemperature
}

func (m *Model) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *Model) GetOutputTokenLimit() *int {
	if m == nil {
		return nil
	}
	return m.OutputTokenLimit
}

func (m *Model) GetSupportedGenerationMethods() []string {
	if m == nil {
		return nil
	}
	return m.SupportedGenerationMethods
}

func (m *Model) GetTemperature() *float32 {
	if m == nil {
		return nil
	}
	return m.Temperature
}

func (m *Model) GetThinking() *bool {
	if m == nil {
		return nil
	}
	return m.Thinking
}

func (m *Model) GetTopK() *int {
	if m == nil {
		return nil
	}
	return m.TopK
}

func (m *Model) GetTopP() *float32 {
	if m == nil {
		return nil
	}
	return m.TopP
}

func (m *Model) GetVersion() *string {
	if m == nil {
		return nil
	}
	return m.Version
}
