// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package files

import (
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/client"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/operations"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

var filesRegisterCmdMeta = []flagutil.FlagMeta{
	{FlagName: "uri", Shorthand: "u", FieldPath: "Body.URI", Kind: flagutil.FlagKindStringArray, Required: true, Description: "Required. The Google Cloud Storage URIs to register. Example: `gs://bucket/object`. [required]"},
}

// initFilesRegisterCmd initializes the files-register command.
func initFilesRegisterCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "register",
		Short:   "Register Google Cloud Storage objects as files without copying them",
		Long:    "Registers Google Cloud Storage objects with the Files API. Pass their gs:// URIs and receive one File resource per URI; the objects are registered in place, not copied. If any URI fails to register, the whole request fails.",
		Example: "  gemini-api files register --uri gs://bucket/object",
		Args:    cobra.NoArgs,
		RunE:    runFilesRegisterCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "FilesRegister",
		},
	}
	flagutil.RegisterFlags(cmd, filesRegisterCmdMeta)
	if err := flagutil.ValidateMeta[operations.FilesRegisterRequest](filesRegisterCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for files-register: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, filesRegisterCmdMeta, "Body", "body"); err != nil {
		return fmt.Errorf("annotate body fields for files-register: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runFilesRegisterCmd executes the files-register command.
func runFilesRegisterCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "FilesRegister")
	}
	req, err := flagutil.BuildRequest[operations.FilesRegisterRequest](cmd, filesRegisterCmdMeta, "Body", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Files.FilesRegister(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
