// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package environments

import (
	"github.com/google-gemini/gemini-api-cli/internal/cli/environments/environmentsfiles"
	"github.com/google-gemini/gemini-api-cli/internal/cli/environments/internal"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitEnvironmentsRoot(parent *cobra.Command) error {
	var EnvironmentsCmd = &cobra.Command{
		Use:         "environments",
		Short:       "Operations for environments",
		Long:        "Operations for environments",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := internal.InitInternalRoot(EnvironmentsCmd); err != nil {
		return err
	}
	if err := environmentsfiles.InitEnvironmentsFilesRoot(EnvironmentsCmd); err != nil {
		return err
	}

	if err := initListEnvironmentsCmd(EnvironmentsCmd); err != nil {
		return err
	}

	if err := initCreateEnvironmentCmd(EnvironmentsCmd); err != nil {
		return err
	}

	if err := initDeleteEnvironmentCmd(EnvironmentsCmd); err != nil {
		return err
	}

	if err := initGetEnvironmentCmd(EnvironmentsCmd); err != nil {
		return err
	}

	parent.AddCommand(EnvironmentsCmd)
	return nil
}
