// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/spf13/cobra"
)

func initCatalogCmds(parent *cobra.Command) error {
	if err := addOrMergeCatalogCmd(parent, newModelsCatalogCmd()); err != nil {
		return fmt.Errorf("register models catalog: %w", err)
	}
	return nil
}

func addOrMergeCatalogCmd(parent *cobra.Command, catalogCmd *cobra.Command) error {
	for _, existing := range parent.Commands() {
		exactName := existing.Name() == catalogCmd.Name()
		if !exactName && !existing.HasAlias(catalogCmd.Name()) {
			continue
		}
		if exactName && existing.Annotations["speakeasy_cli_group"] == "true" && existing.Annotations["speakeasy_cli_promoted"] != "true" {
			existing.RunE = catalogCmd.RunE
			existing.Short = catalogCmd.Short
			if catalogCmd.Long != "" {
				existing.Long = catalogCmd.Long
			}
			return nil
		}
		return fmt.Errorf("x-speakeasy-cli-catalog command %q collides with the existing %q command; rename the catalog command", catalogCmd.Name(), existing.CommandPath())
	}
	parent.AddCommand(catalogCmd)
	return nil
}

func newModelsCatalogCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "models",
		Short: "Show the curated offline model catalog; list/get query the live API",
		Long:  "Bare \"models\" prints the curated model list built into this CLI (offline, no request). The default model is used by \"agent run\" whenever the request body names neither \"model\" nor \"agent\". Use \"models list\" and \"models get\" for the live API's models and metadata.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			values := []map[string]interface{}{
				{"value": "gemini-2.5-flash", "description": "Our first hybrid reasoning model which supports a 1M token context window and has thinking budgets.", "default": false},
				{"value": "gemini-2.5-pro", "description": "Our state-of-the-art multipurpose model, which excels at coding and complex reasoning tasks.", "default": false},
				{"value": "gemma-4-26b-a4b-it", "description": "Gemma 4 26B A4B IT", "default": false},
				{"value": "gemma-4-31b-it", "description": "Gemma 4 31B IT", "default": false},
				{"value": "gemini-flash-latest", "description": "Latest release of Gemini Flash", "default": false},
				{"value": "gemini-flash-lite-latest", "description": "Latest release of Gemini Flash-Lite", "default": false},
				{"value": "gemini-pro-latest", "description": "Latest release of Gemini Pro", "default": false},
				{"value": "gemini-2.5-flash-lite", "description": "Our smallest and most cost effective model, built for at scale usage.", "default": false},
				{"value": "gemini-2.5-flash-image", "description": "Our native image generation model, optimized for speed, flexibility, and contextual understanding. Text input and output is priced the same as 2.5 Flash.", "default": false},
				{"value": "gemini-3-flash-preview", "description": "Our most intelligent model built for speed, combining frontier intelligence with superior search and grounding.", "default": false},
				{"value": "gemini-3.1-pro-preview", "description": "Our latest SOTA reasoning model with unprecedented depth and nuance, and powerful multimodal understanding and coding capabilities.", "default": false},
				{"value": "gemini-3.1-pro-preview-customtools", "description": "Gemini 3.1 Pro Preview optimized for custom tool usage", "default": false},
				{"value": "gemini-3.1-flash-lite", "description": "Our most cost-efficient model, optimized for high-volume agentic tasks, translation, and simple data processing.", "default": false},
				{"value": "gemini-3-pro-image", "description": "Gemini 3 Pro Image", "default": false},
				{"value": "nano-banana-pro-preview", "description": "Gemini 3 Pro Image Preview", "default": false},
				{"value": "gemini-3.1-flash-image", "description": "Gemini 3.1 Flash Image.", "default": false},
				{"value": "gemini-3.1-flash-tts-preview", "description": "Gemini 3.1 Flash TTS: Powerful, low-latency speech generation. Enjoy natural outputs, steerable prompts, and new expressive audio tags for precise narration control.", "default": false},
				{"value": "gemini-3.5-flash", "description": "Our most intelligent model for sustained frontier performance in agentic and coding tasks.", "default": false},
				{"value": "gemini-3.6-flash", "description": "Our most intelligent model for sustained frontier performance in agentic and coding tasks.", "default": true},
				{"value": "gemini-3.7-flash", "description": "Our most intelligent model for sustained frontier performance in agentic and coding tasks.", "default": false},
				{"value": "gemini-3.8-flash", "description": "Our most intelligent model for sustained frontier performance in agentic and coding tasks.", "default": false},
				{"value": "gemini-3.8-flash-tts", "description": "Gemini 3.8 Flash TTS - Flagship TTS model for Voice Design and dual-speaker screenplay control. Prompt custom vocal personas, direct line-by-line delivery, and add vocal bursts.", "default": false},
				{"value": "gemini-3.8-flash-lite-tts", "description": "Gemini 3.8 Flash Lite TTS - High-speed and cost-efficient, ideal for rapid dubbing, media localization, and high-throughput voice agents. Direct replacement for gemini-3.1-flash-tts-preview.", "default": false},
				{"value": "lyria-3-clip-preview", "description": "Our low-latency, music generation model optimized for high-fidelity audio clips and precise rhythmic control.", "default": false},
				{"value": "lyria-3-pro-preview", "description": "Our advanced, full-song generative model with deep compositional understanding, optimized for precise structural control and complex transitions across diverse musical styles.", "default": false},
				{"value": "gemini-robotics-er-1.6-preview", "description": "Gemini Robotics-ER 1.6 Preview", "default": false},
				{"value": "gemini-robotics-er-2-preview", "description": "Gemini Robotics Embodied Reasoning 2 Preview", "default": false},
			}
			if output.IsMachineMode(cmd) {
				return output.LocalResult(cmd, values)
			}
			out := cmd.OutOrStdout()
			fmt.Fprintf(out, "%-42s %s\n", "gemini-2.5-flash", "Our first hybrid reasoning model which supports a 1M token context window and has thinking budgets.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-2.5-pro", "Our state-of-the-art multipurpose model, which excels at coding and complex reasoning tasks.")
			fmt.Fprintf(out, "%-42s %s\n", "gemma-4-26b-a4b-it", "Gemma 4 26B A4B IT")
			fmt.Fprintf(out, "%-42s %s\n", "gemma-4-31b-it", "Gemma 4 31B IT")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-flash-latest", "Latest release of Gemini Flash")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-flash-lite-latest", "Latest release of Gemini Flash-Lite")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-pro-latest", "Latest release of Gemini Pro")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-2.5-flash-lite", "Our smallest and most cost effective model, built for at scale usage.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-2.5-flash-image", "Our native image generation model, optimized for speed, flexibility, and contextual understanding. Text input and output is priced the same as 2.5 Flash.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-3-flash-preview", "Our most intelligent model built for speed, combining frontier intelligence with superior search and grounding.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-3.1-pro-preview", "Our latest SOTA reasoning model with unprecedented depth and nuance, and powerful multimodal understanding and coding capabilities.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-3.1-pro-preview-customtools", "Gemini 3.1 Pro Preview optimized for custom tool usage")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-3.1-flash-lite", "Our most cost-efficient model, optimized for high-volume agentic tasks, translation, and simple data processing.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-3-pro-image", "Gemini 3 Pro Image")
			fmt.Fprintf(out, "%-42s %s\n", "nano-banana-pro-preview", "Gemini 3 Pro Image Preview")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-3.1-flash-image", "Gemini 3.1 Flash Image.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-3.1-flash-tts-preview", "Gemini 3.1 Flash TTS: Powerful, low-latency speech generation. Enjoy natural outputs, steerable prompts, and new expressive audio tags for precise narration control.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-3.5-flash", "Our most intelligent model for sustained frontier performance in agentic and coding tasks.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-3.6-flash (default)", "Our most intelligent model for sustained frontier performance in agentic and coding tasks.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-3.7-flash", "Our most intelligent model for sustained frontier performance in agentic and coding tasks.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-3.8-flash", "Our most intelligent model for sustained frontier performance in agentic and coding tasks.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-3.8-flash-tts", "Gemini 3.8 Flash TTS - Flagship TTS model for Voice Design and dual-speaker screenplay control. Prompt custom vocal personas, direct line-by-line delivery, and add vocal bursts.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-3.8-flash-lite-tts", "Gemini 3.8 Flash Lite TTS - High-speed and cost-efficient, ideal for rapid dubbing, media localization, and high-throughput voice agents. Direct replacement for gemini-3.1-flash-tts-preview.")
			fmt.Fprintf(out, "%-42s %s\n", "lyria-3-clip-preview", "Our low-latency, music generation model optimized for high-fidelity audio clips and precise rhythmic control.")
			fmt.Fprintf(out, "%-42s %s\n", "lyria-3-pro-preview", "Our advanced, full-song generative model with deep compositional understanding, optimized for precise structural control and complex transitions across diverse musical styles.")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-robotics-er-1.6-preview", "Gemini Robotics-ER 1.6 Preview")
			fmt.Fprintf(out, "%-42s %s\n", "gemini-robotics-er-2-preview", "Gemini Robotics Embodied Reasoning 2 Preview")
			return nil
		},
	}
}
