// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"bufio"
	"os"
	"strings"

	"github.com/spf13/cobra"
	"golang.org/x/term"
)

// maskSecret returns a masked version of a secret for display.
// It preserves the first 2 and last 2 characters with a fixed-length
// mask in between to avoid leaking the secret's exact length.
func maskSecret(s string) string {
	if s == "" {
		return "(not set)"
	}
	if len(s) <= 4 {
		return "****"
	}
	return s[:2] + "******" + s[len(s)-2:]
}

// readSecret reads a secret value from the user. When stdin is a terminal,
// it uses term.ReadPassword for hidden input. Otherwise (pipes, tests),
// it falls back to reading a line from cmd.InOrStdin() as plain text.
func readSecret(cmd *cobra.Command) ([]byte, error) {
	if f, ok := cmd.InOrStdin().(*os.File); ok && term.IsTerminal(int(f.Fd())) {
		return term.ReadPassword(int(f.Fd()))
	}

	// Non-terminal fallback: read a line from cmd input (supports test harness piped input)
	reader := bufio.NewReader(cmd.InOrStdin())
	line, err := reader.ReadString('\n')
	if err != nil && line == "" {
		return nil, err
	}
	return []byte(strings.TrimRight(line, "\r\n")), nil
}
