// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/google-gemini/gemini-api-cli/internal/cli/agent"
	"github.com/google-gemini/gemini-api-cli/internal/cli/credentials"
	"github.com/google-gemini/gemini-api-cli/internal/cli/custom"
	"github.com/google-gemini/gemini-api-cli/internal/cli/environments"
	"github.com/google-gemini/gemini-api-cli/internal/cli/files"
	"github.com/google-gemini/gemini-api-cli/internal/cli/models"
	"github.com/google-gemini/gemini-api-cli/internal/cli/triggers"
	"github.com/google-gemini/gemini-api-cli/internal/cli/voices"
	"github.com/google-gemini/gemini-api-cli/internal/cli/webhooks"
	"github.com/google-gemini/gemini-api-cli/internal/clierrors"
	"github.com/google-gemini/gemini-api-cli/internal/config"
	"github.com/google-gemini/gemini-api-cli/internal/explorer"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/interactive"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

var rootCmd *cobra.Command

// NewRootCommand creates and returns the root command.
// This is exported for testing purposes to allow in-process command execution.
func NewRootCommand() (*cobra.Command, error) {
	cobra.AddTemplateFunc("groupedFlagUsages", groupedFlagUsages)
	cobra.AddTemplateFunc("groupedGlobalFlagUsages", groupedGlobalFlagUsages)
	cobra.AddTemplateFunc("compactHelpDefaults", compactHelpDefaults)
	cobra.AddTemplateFunc("compactHelpFooter", compactHelpFooter)
	cobra.AddTemplateFunc("compactRootHelpFooter", compactRootHelpFooter)
	rootCmd := &cobra.Command{
		Use:           "gemini-api",
		Short:         "Gemini API: Use the Gemini Interactions API and managed-agent platform from the command line",
		Long:          "Gemini API: Use the Gemini Interactions API and managed-agent platform from the command line.\n\nGet started:\n  Set GEMINI_API_KEY, or run: gemini-api configure\n  Then run a model or managed agent: gemini-api agent --help\n  Add --dry-run to preview any API call without sending it.",
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			if compactHelpGlobalRequested(cmd) {
				out := cmd.OutOrStdout()
				fmt.Fprintln(out, "Global flags (apply to every command):")
				fmt.Fprintln(out)
				_, err := fmt.Fprintln(out, renderGroupedFlags(cmd.Root().PersistentFlags(), "Global Flags"))
				return err
			}
			return cmd.Help()
		},
		PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
			if compactHelpGlobalRequested(cmd) {
				return nil
			}
			if usage.UsageRequested(cmd) {
				return nil
			}
			if err := flagutil.ValidateOutputFormatFlag(cmd, output.Formats); err != nil {
				return err
			}
			if err := flagutil.ValidateEnumFlag(cmd, "color", []string{"auto", "always", "never"}); err != nil {
				return err
			}
			if err := config.Init("gemini-api", "GEMINI"); err != nil {
				return err
			}
			output.InitAgentMode(cmd)
			flagutil.SetStdinReadDeadline(output.IsAgentMode())
			return nil
		},
	}
	rootCmd.Flags().Bool("help-global", false, "Print global flags shared by every command")
	if err := agent.InitAgentRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init agent: %w", err)
	}
	if err := credentials.InitCredentialsRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init credentials: %w", err)
	}
	if err := environments.InitEnvironmentsRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init environments: %w", err)
	}
	if err := files.InitFilesRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init files: %w", err)
	}
	if err := models.InitModelsRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init models: %w", err)
	}
	if err := triggers.InitTriggersRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init triggers: %w", err)
	}
	if err := voices.InitVoicesRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init voices: %w", err)
	}
	if err := webhooks.InitWebhooksRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init webhooks: %w", err)
	}
	if err := initConfigureCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init configure: %w", err)
	}
	if err := initWhoamiCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init whoami: %w", err)
	}
	if err := initVersionCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init version: %w", err)
	}
	if err := initAuthCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init auth: %w", err)
	}
	initExploreCmd(rootCmd)
	if err := initCatalogCmds(rootCmd); err != nil {
		return nil, fmt.Errorf("init catalogs: %w", err)
	}

	// Global output format flag
	rootCmd.PersistentFlags().StringP("output-format", "o", "pretty", "Specify the output format. Options: "+strings.Join(output.Formats, ", ")+".")

	// Color control flag
	rootCmd.PersistentFlags().String("color", "auto", "Control colored output: auto (color when output is a TTY), always, or never. Respects NO_COLOR and FORCE_COLOR env vars.")

	// jq filtering flag
	rootCmd.PersistentFlags().StringP("jq", "q", "", "Filter and transform output using a jq expression (e.g., '.name', '.items[] | .id')")
	rootCmd.PersistentFlags().Bool("raw-output", true, "Write --jq string results as raw text instead of JSON strings (like jq -r); non-string results stay JSON")

	// Global server URL flag
	rootCmd.PersistentFlags().String("server-url", "", "Override the default server URL")

	// Custom header flag (repeatable: --header "Key: Value" --header "Key2: Value2")
	rootCmd.PersistentFlags().StringArrayP("header", "H", nil, "Set a custom HTTP request header (format: \"Key: Value\"). Can be specified multiple times.")

	// Response headers flag
	rootCmd.PersistentFlags().Bool("include-headers", false, "Include HTTP response headers in the output")

	// Request timeout (always available)
	rootCmd.PersistentFlags().String("timeout", "", "HTTP request timeout (e.g., 30s, 5m, 100ms)")
	rootCmd.PersistentFlags().Bool("interactive", false, "Prompt for missing inputs and open guided configure/auth forms (forms fall back to line prompts on stdin off-TTY)")
	rootCmd.PersistentFlags().Bool("no-interactive", false, "Disable all interactive features (auto-prompting, explorer auto-launch, TUI forms)")

	// Diagnostics flags
	rootCmd.PersistentFlags().Bool("usage", false, "Print the CLI Usage schema in KDL format")
	rootCmd.PersistentFlags().Bool("dry-run", false, "Preview API requests without sending them (no network, no OS keychain). Human preview on stderr; with -o json or --jq, one JSON object per request on stdout. Local mutation commands (auth login, auth logout and configure) make no request: they skip prompts and writes and report a no-op (stderr, or one JSON object on stdout in the machine form)")
	rootCmd.PersistentFlags().BoolP("debug", "d", false, "Log request and response diagnostics to stderr")

	// Agent mode — optimized output for AI coding agent consumption.
	rootCmd.PersistentFlags().Bool("agent-mode", false,
		"Enable structured errors and default TOON output for AI coding agents.")
	// Retry control flags
	// Defaults: exponential backoff, 500ms initial / 10s max interval, 1.5x exponent, 30s max elapsed time.
	rootCmd.PersistentFlags().Bool("no-retries", false, "Disable automatic retries (default: retries enabled with exponential backoff)")
	rootCmd.PersistentFlags().String("retry-max-elapsed-time", "", "Maximum total time for retries (e.g., 30s, 5m). Default: 30s")
	rootCmd.PersistentFlags().Bool("retry-connection-errors", false, "Retry on connection errors (EOF, reset, etc.)")
	rootCmd.PersistentFlags().String("retry-config", "", `Full retry config as JSON. Schema: {"strategy":"backoff","backoff":{"initialInterval":500,"maxInterval":10000,"exponent":1.5,"maxElapsedTime":30000},"retryConnectionErrors":false}. Use strategy "attempt-count-backoff" with maxRetries for attempt-count retries. Times are in milliseconds.`)
	for _, flag := range []string{"no-retries", "retry-max-elapsed-time", "retry-connection-errors", "retry-config"} {
		_ = rootCmd.PersistentFlags().MarkHidden(flag)
	}

	// Global security flags
	rootCmd.PersistentFlags().String("api-key", "", "Gemini API key sent as x-goog-api-key.")
	_ = rootCmd.PersistentFlags().SetAnnotation("api-key", "speakeasy:group", []string{"Authentication"})
	rootCmd.PersistentFlags().String("access-token", "", "OAuth access token sent as a bearer Authorization header.")
	_ = rootCmd.PersistentFlags().SetAnnotation("access-token", "speakeasy:group", []string{"Authentication"})
	// Global parameter flags
	rootCmd.PersistentFlags().String("api-version", "v1beta", "Which version of the API to use (env: GEMINI_API_VERSION)")
	_ = rootCmd.PersistentFlags().SetAnnotation("api-version", "speakeasy:group", []string{"API Parameters"})
	rootCmd.PersistentFlags().String("api-revision", "", "Interactions API revision to request (env: GEMINI_API_REVISION)")
	_ = rootCmd.PersistentFlags().SetAnnotation("api-revision", "speakeasy:group", []string{"API Parameters"})
	rootCmd.PersistentFlags().String("user-project", "", "Quota project header to send with Google GenAI API requests (env: GEMINI_USER_PROJECT)")
	_ = rootCmd.PersistentFlags().SetAnnotation("user-project", "speakeasy:group", []string{"API Parameters"})

	// Annotate persistent flags for grouped help display
	for _, ga := range []struct{ flag, group string }{
		{"output-format", "Output"},
		{"color", "Output"},
		{"raw-output", "Output"},
		{"jq", "Output"},
		{"include-headers", "Output"},
		{"interactive", "Output"},
		{"no-interactive", "Output"},
		{"server-url", "Server"},
		{"header", "Network"},
		{"timeout", "Network"},
		{"usage", "Diagnostics"},
		{"dry-run", "Diagnostics"},
		{"debug", "Diagnostics"},
		{"agent-mode", "Diagnostics"},
	} {
		_ = rootCmd.PersistentFlags().SetAnnotation(ga.flag, "speakeasy:group", []string{ga.group})
	}
	for _, flag := range []string{"no-retries", "retry-max-elapsed-time", "retry-connection-errors", "retry-config"} {
		_ = rootCmd.PersistentFlags().SetAnnotation(flag, "speakeasy:group", []string{"Network"})
	}

	rootCmd.SetUsageTemplate(groupedUsageTemplate())

	if err := initIntentCmds(rootCmd); err != nil {
		return nil, err
	}

	custom.Register(rootCmd)

	// Cobra creates its default help and completion commands lazily inside Execute.
	rootCmd.InitDefaultHelpCmd()
	rootCmd.InitDefaultCompletionCmd()
	applyDeclaredCommandOrder(rootCmd)
	interactive.Intercept(rootCmd)
	usage.Intercept(rootCmd)
	// Cobra validates Args before any PersistentPreRunE runs.
	output.InstallErrorHandling(rootCmd)

	return rootCmd, nil
}

func Execute() error {
	var err error
	rootCmd, err = NewRootCommand()
	if err != nil {
		return err
	}

	return ExecuteRoot(context.Background(), rootCmd, os.Args[1:])
}

func ExecuteRoot(ctx context.Context, root *cobra.Command, args []string) error {
	// Cobra aborts on an unknown command or flag before PersistentPreRunE runs.
	output.InitAgentMode(root)
	target, _, findErr := root.Find(args)
	if findErr != nil || target == nil {
		target = root
	}
	output.PreparseRenderingFlags(target, args)
	root.SetArgs(args)
	executed, err := root.ExecuteContextC(ctx)
	if executed == nil {
		executed = root
	}
	if err != nil && findErr != nil {
		err = flagutil.WithCLIValidation(err)
	}
	return output.CLIError(executed, err)
}

func initExploreCmd(parent *cobra.Command) {
	parent.AddCommand(&cobra.Command{
		Use:   "explore",
		Short: "Interactively browse and run commands",
		Long:  "Launch an interactive command explorer to browse available commands, view their descriptions and flags, and execute them.",
		RunE: func(cmd *cobra.Command, args []string) error {
			// Agent mode: print help instead of launching TUI.
			if output.IsAgentMode() {
				return cmd.Root().Help()
			}
			if err := interactive.Resolve(cmd).ValidateDirectExplore(); err != nil {
				return err
			}
			return runExplorer(cmd.Root())
		},
	})
}

func ExplorerHandoffArgs(root *cobra.Command, selectedArgs []string) []string {
	interactionFlag := "--interactive"
	if noInteractive, _ := root.PersistentFlags().GetBool("no-interactive"); noInteractive {
		interactionFlag = "--no-interactive"
	}
	handoffArgs := []string{interactionFlag}
	if dryRun, _ := root.PersistentFlags().GetBool("dry-run"); dryRun {
		handoffArgs = append(handoffArgs, "--dry-run")
	}
	if debug, _ := root.PersistentFlags().GetBool("debug"); debug {
		handoffArgs = append(handoffArgs, "--debug")
	}
	// Rendering flags given to the explore invocation apply to the selected
	// command: the fresh command tree re-parses argv (and resets the
	// preparsed rendering state), so they must travel with it. The
	// --name=value form keeps boolean flags from swallowing the next token.
	for _, name := range []string{"output-format", "jq", "raw-output", "color"} {
		if flag := root.PersistentFlags().Lookup(name); flag != nil && flag.Changed {
			handoffArgs = append(handoffArgs, "--"+name+"="+flag.Value.String())
		}
	}
	return append(handoffArgs, selectedArgs...)
}

// runExplorer launches the explorer TUI and handles command execution handoff.
func runExplorer(root *cobra.Command) error {
	selectedArgs, err := explorer.Run(root, Version)
	if err != nil {
		return err
	}
	if selectedArgs == nil {
		return nil // user quit
	}
	// Build a fresh command tree and execute the selected command
	freshRoot, err := NewRootCommand()
	if err != nil {
		return err
	}
	return ExecuteRoot(context.Background(), freshRoot, ExplorerHandoffArgs(root, selectedArgs))
}

// globalFlagGroupOrder defines the display order for flag groups in help output.
// Groups without any flags are skipped automatically.
var globalFlagGroupOrder = []string{"Output", "Authentication", "API Parameters", "Server", "Network", "Diagnostics"}

// groupedFlagUsages splits local flags into sections for help display.
// For operation commands (flags with "speakeasy:required"): Required/Optional sections.
// For the root command (flags with "speakeasy:group"): category-based sections.
// Falls back to a flat "Flags:" listing otherwise.
func groupedFlagUsages(flags *pflag.FlagSet) string {
	required := pflag.NewFlagSet("required", pflag.ContinueOnError)
	optional := pflag.NewFlagSet("optional", pflag.ContinueOnError)
	hasGroupAnnotation := false

	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		if ann, ok := f.Annotations["speakeasy:required"]; ok && len(ann) > 0 && ann[0] == "true" {
			required.AddFlag(f)
		} else {
			optional.AddFlag(f)
		}
		if _, ok := f.Annotations["speakeasy:group"]; ok {
			hasGroupAnnotation = true
		}
	})

	// Operation commands: Required/Optional sections, with sub-groups when present
	if required.HasFlags() {
		var buf strings.Builder
		buf.WriteString("Required Flags:\n")
		buf.WriteString(required.FlagUsages())
		if optional.HasFlags() {
			if hasGroupAnnotation {
				buf.WriteString("\n")
				buf.WriteString(renderOperationGroups(optional))
			} else {
				buf.WriteString("\nOptional Flags:\n")
				buf.WriteString(optional.FlagUsages())
			}
		}
		return strings.TrimRight(buf.String(), "\n")
	}

	// Grouped flags (root command or operation with only optional grouped flags)
	if hasGroupAnnotation {
		// Check if any groups are in the global order (root-level groups like Output, Server)
		hasGlobalGroup := false
		flags.VisitAll(func(f *pflag.Flag) {
			if ann, ok := f.Annotations["speakeasy:group"]; ok && len(ann) > 0 {
				for _, g := range globalFlagGroupOrder {
					if ann[0] == g {
						hasGlobalGroup = true
					}
				}
			}
		})
		if hasGlobalGroup {
			return renderGroupedFlags(flags, "Flags")
		}
		// Operation-level groups (e.g., Address, Profile)
		return strings.TrimRight(renderOperationGroups(flags), "\n")
	}

	// Fallback: flat listing
	return "Flags:\n" + strings.TrimRight(flags.FlagUsages(), "\n")
}

// groupedGlobalFlagUsages splits inherited (global) flags into category sections
// based on the "speakeasy:group" annotation. Falls back to flat "Global Flags:".
func groupedGlobalFlagUsages(flags *pflag.FlagSet) string {
	hasGroupAnnotation := false
	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		if _, ok := f.Annotations["speakeasy:group"]; ok {
			hasGroupAnnotation = true
		}
	})

	if hasGroupAnnotation {
		return renderGroupedFlags(flags, "Global Flags")
	}

	return "Global Flags:\n" + strings.TrimRight(flags.FlagUsages(), "\n")
}

// renderOperationGroups renders optional operation flags grouped by their
// "speakeasy:group" annotation. Groups are shown alphabetically, with
// ungrouped flags under a generic "Optional Flags" header.
func renderOperationGroups(flags *pflag.FlagSet) string {
	groups := make(map[string]*pflag.FlagSet)
	groupOrder := []string{}
	groupOrders := make(map[string]int)
	ungrouped := pflag.NewFlagSet("ungrouped", pflag.ContinueOnError)

	parseOrder := func(raw string) (int, bool) {
		if raw == "" {
			return 0, false
		}
		sign, start := 1, 0
		if raw[0] == '-' {
			sign, start = -1, 1
		}
		if start == len(raw) {
			return 0, false
		}
		value := 0
		for i := start; i < len(raw); i++ {
			if raw[i] < '0' || raw[i] > '9' {
				return 0, false
			}
			value = value*10 + int(raw[i]-'0')
		}
		return sign * value, true
	}

	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		if ann, ok := f.Annotations["speakeasy:group"]; ok && len(ann) > 0 {
			name := ann[0]
			if _, exists := groups[name]; !exists {
				groups[name] = pflag.NewFlagSet(name, pflag.ContinueOnError)
				groupOrder = append(groupOrder, name)
			}
			groups[name].AddFlag(f)
			if orderAnn, ok := f.Annotations["speakeasy:group-order"]; ok && len(orderAnn) > 0 {
				if order, valid := parseOrder(orderAnn[0]); valid {
					current, exists := groupOrders[name]
					if !exists || order < current {
						groupOrders[name] = order
					}
				}
			}
		} else {
			ungrouped.AddFlag(f)
		}
	})

	for i := 1; i < len(groupOrder); i++ {
		for j := i; j > 0; j-- {
			current, currentOrdered := groupOrders[groupOrder[j]]
			previous, previousOrdered := groupOrders[groupOrder[j-1]]
			if !currentOrdered || (previousOrdered && current >= previous) {
				break
			}
			groupOrder[j], groupOrder[j-1] = groupOrder[j-1], groupOrder[j]
		}
	}

	var buf strings.Builder

	// Show ungrouped optional flags first
	if ungrouped.HasFlags() {
		buf.WriteString("Optional Flags:\n")
		buf.WriteString(ungrouped.FlagUsages())
	}

	// Then show each group
	for _, name := range groupOrder {
		fs := groups[name]
		if !fs.HasFlags() {
			continue
		}
		buf.WriteString("\n" + name + " Flags:\n")
		buf.WriteString(fs.FlagUsages())
	}

	return buf.String()
}

// renderGroupedFlags groups flags by their "speakeasy:group" annotation,
// rendering each group as a separate section with a header. Flags without
// a group annotation are collected under the fallbackHeader section.
func renderGroupedFlags(flags *pflag.FlagSet, fallbackHeader string) string {
	groups := make(map[string]*pflag.FlagSet)
	for _, g := range globalFlagGroupOrder {
		groups[g] = pflag.NewFlagSet(g, pflag.ContinueOnError)
	}
	ungrouped := pflag.NewFlagSet("ungrouped", pflag.ContinueOnError)

	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		if ann, ok := f.Annotations["speakeasy:group"]; ok && len(ann) > 0 {
			if fs, exists := groups[ann[0]]; exists {
				fs.AddFlag(f)
				return
			}
		}
		ungrouped.AddFlag(f)
	})

	var buf strings.Builder
	first := true
	for _, name := range globalFlagGroupOrder {
		fs := groups[name]
		if !fs.HasFlags() {
			continue
		}
		if !first {
			buf.WriteString("\n")
		}
		buf.WriteString(name + ":\n")
		buf.WriteString(fs.FlagUsages())
		first = false
	}
	if ungrouped.HasFlags() {
		if !first {
			buf.WriteString("\n")
		}
		buf.WriteString(fallbackHeader + ":\n")
		buf.WriteString(ungrouped.FlagUsages())
	}
	return strings.TrimRight(buf.String(), "\n")
}

func compactHelpGlobalRequested(cmd *cobra.Command) bool {
	if cmd == nil || cmd.Root() == nil {
		return false
	}
	requested, err := cmd.Root().Flags().GetBool("help-global")
	return err == nil && requested
}

func compactMachineInterface(cmd *cobra.Command) string {
	if cmd == nil || cmd.Root() == nil {
		return ""
	}
	cmd.InheritedFlags()
	has := func(name string) bool {
		return cmd.Flags().Lookup(name) != nil || cmd.InheritedFlags().Lookup(name) != nil
	}
	parts := []string{}
	if has("json") {
		parts = append(parts, "--json")
	} else if has("output-format") {
		parts = append(parts, "--output-format json")
	}
	if has("transform") {
		parts = append(parts, "--transform <dot.path>")
	} else if has("jq") {
		parts = append(parts, "--jq <expr>")
	}
	if has("raw") {
		parts = append(parts, "--raw")
	}
	if has("dry-run") {
		parts = append(parts, "--dry-run")
	}
	if has("usage") {
		parts = append(parts, "--usage")
	}
	return strings.Join(parts, " · ")
}

func compactHelpDefaults(cmd *cobra.Command) string {
	if cmd == nil || cmd.Annotations == nil {
		return ""
	}
	return cmd.Annotations["speakeasy_help_defaults"]
}

func compactHelpFooter(cmd *cobra.Command) string {
	if cmd == nil || cmd.Annotations["speakeasy_help_footer"] == "false" {
		return ""
	}
	lines := []string{}
	if machine := compactMachineInterface(cmd); machine != "" {
		lines = append(lines, "Machine interface: "+machine)
	}
	lines = append(lines, "Globals (auth, network, output): "+cmd.Root().Name()+" --help-global")
	learn := cmd.Annotations["speakeasy_help_learn"]
	escalate := cmd.Annotations["speakeasy_help_escalate"]
	switch {
	case learn != "" && escalate != "":
		lines = append(lines, "Learn: "+learn+" · escalate: "+escalate)
	case learn != "":
		lines = append(lines, "Learn: "+learn)
	case escalate != "":
		lines = append(lines, "Escalate: "+escalate)
	}
	return strings.Join(lines, string(rune(10)))
}

func compactRootHelpFooter(cmd *cobra.Command) string {
	if cmd == nil || cmd.Root() == nil {
		return ""
	}
	rootName := cmd.Root().Name()
	lines := []string{}
	if machine := compactMachineInterface(cmd); machine != "" {
		lines = append(lines, "Machine interface: "+machine)
	}
	lines = append(lines, "Globals (auth, network, output): "+rootName+" --help-global")
	lines = append(lines, "Setup: export GEMINI_API_KEY=...   or   "+rootName+" configure")
	return strings.Join(lines, string(rune(10)))
}

// groupedUsageTemplate returns Cobra's default usage template with the local
// and global Flags sections replaced to use grouped rendering.
// Built at runtime via strings.Replace to avoid template delimiter conflicts
// with the code generator's own template engine.
func groupedUsageTemplate() string {
	ob := string([]byte{'{', '{'})
	cb := string([]byte{'}', '}'})
	nl := string(rune(10))
	defaultTmpl := (&cobra.Command{}).UsageTemplate()

	oldLocalCondition := ob + "if .HasAvailableLocalFlags" + cb
	oldLocal := oldLocalCondition + nl + nl + "Flags:" + nl + ob + ".LocalFlags.FlagUsages | trimTrailingWhitespaces" + cb + ob + "end" + cb
	newLocalCondition := ob + "if and .HasParent .HasAvailableLocalFlags" + cb
	newLocal := newLocalCondition + nl + nl + ob + "groupedFlagUsages .LocalFlags | trimTrailingWhitespaces" + cb + ob + "end" + cb
	result := strings.Replace(defaultTmpl, oldLocal, newLocal, 1)

	defaults := ob + "with compactHelpDefaults ." + cb + nl + nl + "Defaults: " + ob + "." + cb + ob + "end" + cb
	result = strings.Replace(result, newLocalCondition, defaults+newLocalCondition, 1)

	oldGlobal := ob + "if .HasAvailableInheritedFlags" + cb + nl + nl + "Global Flags:" + nl + ob + ".InheritedFlags.FlagUsages | trimTrailingWhitespaces" + cb + ob + "end" + cb
	result = strings.Replace(result, oldGlobal, "", 1)

	result = strings.Replace(result, nl+nl+"Examples:"+nl, nl+nl+"Just works:"+nl, 1)

	oldFooter := ob + "if .HasAvailableSubCommands" + cb + nl + nl + "Use \"" + ob + ".CommandPath" + cb + " [command] --help\" for more information about a command." + ob + "end" + cb
	rootFooter := ob + "if not .HasParent" + cb + ob + "with compactRootHelpFooter ." + cb + nl + nl + ob + "." + cb + ob + "end" + cb + ob + "end" + cb
	commandFooter := ob + "if .HasParent" + cb + ob + "with compactHelpFooter ." + cb + nl + nl + ob + "." + cb + ob + "end" + cb + ob + "end" + cb
	result = strings.Replace(result, oldFooter, rootFooter+oldFooter+commandFooter, 1)

	result = strings.TrimRight(result, nl) + nl + nl + clierrors.HelpFooter + nl

	return result
}
