// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/config"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

// initWhoamiCmd initializes the whoami command.
func initWhoamiCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:   "whoami",
		Short: "Display current authentication and global parameter configuration",
		Long: `Display the currently configured settings and their sources.

Sources are shown as:
  [flag]    - Set via command line flag
  [env]     - Set via environment variable (GEMINI_*)
  [keyring] - Set via OS keychain (stored by configure command)
  [config]  - Set via config file (~/.config/gemini-api/config.yaml)
  [unset]   - Not configured

Credential values are masked for security.`,
		Args: cobra.NoArgs,
		RunE: runWhoamiCmd,
	}
	parent.AddCommand(cmd)
	return nil
}

// runWhoamiCmd executes the whoami command.
func runWhoamiCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}

	if output.IsMachineMode(cmd) {
		info := map[string]any{
			"config_file":        config.GetConfigPath(),
			"environment_prefix": "GEMINI_",
		}
		credentials := map[string]any{}
		{
			value, source := config.ResolveSecurityCredential(cmd, "api-key")
			credentials["api-key"] = map[string]any{"source": source, "value": maskSecret(value)}
		}
		{
			value, source := config.ResolveSecurityCredential(cmd, "access-token")
			credentials["access-token"] = map[string]any{"source": source, "value": maskSecret(value)}
		}
		info["credentials"] = credentials
		parameters := map[string]any{}
		{
			value, source := config.ResolveCredential(cmd, "api-version")
			parameters["api-version"] = map[string]any{"source": source, "value": value}
		}
		{
			value, source := config.ResolveCredential(cmd, "api-revision")
			parameters["api-revision"] = map[string]any{"source": source, "value": value}
		}
		{
			value, source := config.ResolveCredential(cmd, "user-project")
			parameters["user-project"] = map[string]any{"source": source, "value": value}
		}
		info["global_parameters"] = parameters
		return output.LocalResult(cmd, info)
	}

	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "Configuration")
	fmt.Fprintln(out, "=============")
	fmt.Fprintln(out)
	fmt.Fprintf(out, "Config file: %s\n", config.GetConfigPath())
	fmt.Fprintf(out, "Environment prefix: GEMINI_\n")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "Credentials:")

	// Gemini API key sent as x-goog-api-key.
	{
		value, source := config.ResolveSecurityCredential(cmd, "api-key")
		fmt.Fprintf(out, "  --%-25s [%-7s] %s\n", "api-key", source, maskSecret(value))
	}

	// OAuth access token sent as a bearer Authorization header.
	{
		value, source := config.ResolveSecurityCredential(cmd, "access-token")
		fmt.Fprintf(out, "  --%-25s [%-7s] %s\n", "access-token", source, maskSecret(value))
	}

	fmt.Fprintln(out)
	fmt.Fprintln(out, "Global Parameters:")

	// Which version of the API to use
	{
		value, source := config.ResolveCredential(cmd, "api-version")
		fmt.Fprintf(out, "  --%-25s [%-7s] %s\n", "api-version", source, value)
	}

	// Interactions API revision to request
	{
		value, source := config.ResolveCredential(cmd, "api-revision")
		fmt.Fprintf(out, "  --%-25s [%-7s] %s\n", "api-revision", source, value)
	}

	// Quota project header to send with Google GenAI API requests
	{
		value, source := config.ResolveCredential(cmd, "user-project")
		fmt.Fprintf(out, "  --%-25s [%-7s] %s\n", "user-project", source, value)
	}

	return nil
}
