// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"

	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type FunctionResultDeltaResultType string

const (
	FunctionResultDeltaResultTypeArrayOfFunctionResultSubcontent FunctionResultDeltaResultType = "arrayOfFunctionResultSubcontent"
	FunctionResultDeltaResultTypeMapOfAny                        FunctionResultDeltaResultType = "mapOfAny"
	FunctionResultDeltaResultTypeStr                             FunctionResultDeltaResultType = "str"
	FunctionResultDeltaResultTypeUnknown                         FunctionResultDeltaResultType = "Unknown"
)

type FunctionResultDeltaResult struct {
	ArrayOfFunctionResultSubcontent []FunctionResultSubcontent `queryParam:"inline" union:"member"`
	MapOfAny                        map[string]any             `queryParam:"inline" union:"member"`
	Str                             *string                    `queryParam:"inline" union:"member"`
	UnknownRaw                      json.RawMessage            `json:"-" union:"unknown"`

	Type FunctionResultDeltaResultType
}

func CreateFunctionResultDeltaResultArrayOfFunctionResultSubcontent(arrayOfFunctionResultSubcontent []FunctionResultSubcontent) FunctionResultDeltaResult {
	typ := FunctionResultDeltaResultTypeArrayOfFunctionResultSubcontent

	return FunctionResultDeltaResult{
		ArrayOfFunctionResultSubcontent: arrayOfFunctionResultSubcontent,
		Type:                            typ,
	}
}

func CreateFunctionResultDeltaResultMapOfAny(mapOfAny map[string]any) FunctionResultDeltaResult {
	typ := FunctionResultDeltaResultTypeMapOfAny

	return FunctionResultDeltaResult{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func CreateFunctionResultDeltaResultStr(str string) FunctionResultDeltaResult {
	typ := FunctionResultDeltaResultTypeStr

	return FunctionResultDeltaResult{
		Str:  &str,
		Type: typ,
	}
}

func CreateFunctionResultDeltaResultUnknown(raw json.RawMessage) FunctionResultDeltaResult {
	return FunctionResultDeltaResult{
		UnknownRaw: raw,
		Type:       FunctionResultDeltaResultTypeUnknown,
	}
}

func (u FunctionResultDeltaResult) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u FunctionResultDeltaResult) IsUnknown() bool {
	return u.Type == FunctionResultDeltaResultTypeUnknown
}

func (u *FunctionResultDeltaResult) UnmarshalJSON(data []byte) error {
	*u = FunctionResultDeltaResult{}

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var arrayOfFunctionResultSubcontent []FunctionResultSubcontent = []FunctionResultSubcontent{}
	if err := utils.UnmarshalJSON(data, &arrayOfFunctionResultSubcontent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FunctionResultDeltaResultTypeArrayOfFunctionResultSubcontent,
			Value: arrayOfFunctionResultSubcontent,
		})
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FunctionResultDeltaResultTypeMapOfAny,
			Value: mapOfAny,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FunctionResultDeltaResultTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FunctionResultDeltaResultTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FunctionResultDeltaResultTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(FunctionResultDeltaResultType)
	switch best.Type {
	case FunctionResultDeltaResultTypeArrayOfFunctionResultSubcontent:
		u.ArrayOfFunctionResultSubcontent = best.Value.([]FunctionResultSubcontent)
		return nil
	case FunctionResultDeltaResultTypeMapOfAny:
		u.MapOfAny = best.Value.(map[string]any)
		return nil
	case FunctionResultDeltaResultTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = FunctionResultDeltaResultTypeUnknown
	return nil
}

func (u FunctionResultDeltaResult) MarshalJSON() ([]byte, error) {
	if u.ArrayOfFunctionResultSubcontent != nil {
		return utils.MarshalJSON(u.ArrayOfFunctionResultSubcontent, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type FunctionResultDeltaResult: all fields are null")
}

type FunctionResultDelta struct {
	IsError *bool                     `json:"is_error,omitzero"`
	Name    *string                   `json:"name,omitzero"`
	Result  FunctionResultDeltaResult `json:"result"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"function_result" json:"type"`
}

func (f FunctionResultDelta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionResultDelta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionResultDelta) GetIsError() *bool {
	if f == nil {
		return nil
	}
	return f.IsError
}

func (f *FunctionResultDelta) GetName() *string {
	if f == nil {
		return nil
	}
	return f.Name
}

func (f *FunctionResultDelta) GetResult() FunctionResultDeltaResult {
	if f == nil {
		return FunctionResultDeltaResult{}
	}
	return f.Result
}

func (f *FunctionResultDelta) GetType() string {
	return "function_result"
}
