// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"

	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type MCPServerToolResultDeltaResultType string

const (
	MCPServerToolResultDeltaResultTypeArrayOfFunctionResultSubcontent MCPServerToolResultDeltaResultType = "arrayOfFunctionResultSubcontent"
	MCPServerToolResultDeltaResultTypeMapOfAny                        MCPServerToolResultDeltaResultType = "mapOfAny"
	MCPServerToolResultDeltaResultTypeStr                             MCPServerToolResultDeltaResultType = "str"
	MCPServerToolResultDeltaResultTypeUnknown                         MCPServerToolResultDeltaResultType = "Unknown"
)

type MCPServerToolResultDeltaResult struct {
	ArrayOfFunctionResultSubcontent []FunctionResultSubcontent `queryParam:"inline" union:"member"`
	MapOfAny                        map[string]any             `queryParam:"inline" union:"member"`
	Str                             *string                    `queryParam:"inline" union:"member"`
	UnknownRaw                      json.RawMessage            `json:"-" union:"unknown"`

	Type MCPServerToolResultDeltaResultType
}

func CreateMCPServerToolResultDeltaResultArrayOfFunctionResultSubcontent(arrayOfFunctionResultSubcontent []FunctionResultSubcontent) MCPServerToolResultDeltaResult {
	typ := MCPServerToolResultDeltaResultTypeArrayOfFunctionResultSubcontent

	return MCPServerToolResultDeltaResult{
		ArrayOfFunctionResultSubcontent: arrayOfFunctionResultSubcontent,
		Type:                            typ,
	}
}

func CreateMCPServerToolResultDeltaResultMapOfAny(mapOfAny map[string]any) MCPServerToolResultDeltaResult {
	typ := MCPServerToolResultDeltaResultTypeMapOfAny

	return MCPServerToolResultDeltaResult{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func CreateMCPServerToolResultDeltaResultStr(str string) MCPServerToolResultDeltaResult {
	typ := MCPServerToolResultDeltaResultTypeStr

	return MCPServerToolResultDeltaResult{
		Str:  &str,
		Type: typ,
	}
}

func CreateMCPServerToolResultDeltaResultUnknown(raw json.RawMessage) MCPServerToolResultDeltaResult {
	return MCPServerToolResultDeltaResult{
		UnknownRaw: raw,
		Type:       MCPServerToolResultDeltaResultTypeUnknown,
	}
}

func (u MCPServerToolResultDeltaResult) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u MCPServerToolResultDeltaResult) IsUnknown() bool {
	return u.Type == MCPServerToolResultDeltaResultTypeUnknown
}

func (u *MCPServerToolResultDeltaResult) UnmarshalJSON(data []byte) error {
	*u = MCPServerToolResultDeltaResult{}

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var arrayOfFunctionResultSubcontent []FunctionResultSubcontent = []FunctionResultSubcontent{}
	if err := utils.UnmarshalJSON(data, &arrayOfFunctionResultSubcontent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MCPServerToolResultDeltaResultTypeArrayOfFunctionResultSubcontent,
			Value: arrayOfFunctionResultSubcontent,
		})
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MCPServerToolResultDeltaResultTypeMapOfAny,
			Value: mapOfAny,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MCPServerToolResultDeltaResultTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = MCPServerToolResultDeltaResultTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = MCPServerToolResultDeltaResultTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(MCPServerToolResultDeltaResultType)
	switch best.Type {
	case MCPServerToolResultDeltaResultTypeArrayOfFunctionResultSubcontent:
		u.ArrayOfFunctionResultSubcontent = best.Value.([]FunctionResultSubcontent)
		return nil
	case MCPServerToolResultDeltaResultTypeMapOfAny:
		u.MapOfAny = best.Value.(map[string]any)
		return nil
	case MCPServerToolResultDeltaResultTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = MCPServerToolResultDeltaResultTypeUnknown
	return nil
}

func (u MCPServerToolResultDeltaResult) MarshalJSON() ([]byte, error) {
	if u.ArrayOfFunctionResultSubcontent != nil {
		return utils.MarshalJSON(u.ArrayOfFunctionResultSubcontent, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type MCPServerToolResultDeltaResult: all fields are null")
}

type MCPServerToolResultDelta struct {
	Name       *string                        `json:"name,omitzero"`
	Result     MCPServerToolResultDeltaResult `json:"result"`
	ServerName *string                        `json:"server_name,omitzero"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"mcp_server_tool_result" json:"type"`
}

func (m MCPServerToolResultDelta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MCPServerToolResultDelta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MCPServerToolResultDelta) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MCPServerToolResultDelta) GetResult() MCPServerToolResultDeltaResult {
	if m == nil {
		return MCPServerToolResultDeltaResult{}
	}
	return m.Result
}

func (m *MCPServerToolResultDelta) GetServerName() *string {
	if m == nil {
		return nil
	}
	return m.ServerName
}

func (m *MCPServerToolResultDelta) GetType() string {
	return "mcp_server_tool_result"
}
