// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"

	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type MCPServerToolResultStepResultType string

const (
	MCPServerToolResultStepResultTypeArrayOfFunctionResultSubcontent MCPServerToolResultStepResultType = "arrayOfFunctionResultSubcontent"
	MCPServerToolResultStepResultTypeMapOfAny                        MCPServerToolResultStepResultType = "mapOfAny"
	MCPServerToolResultStepResultTypeStr                             MCPServerToolResultStepResultType = "str"
	MCPServerToolResultStepResultTypeUnknown                         MCPServerToolResultStepResultType = "Unknown"
)

// MCPServerToolResultStepResult - Required. The output from the MCP server call. Can be simple text or rich content.
type MCPServerToolResultStepResult struct {
	ArrayOfFunctionResultSubcontent []FunctionResultSubcontent `queryParam:"inline" union:"member"`
	MapOfAny                        map[string]any             `queryParam:"inline" union:"member"`
	Str                             *string                    `queryParam:"inline" union:"member"`
	UnknownRaw                      json.RawMessage            `json:"-" union:"unknown"`

	Type MCPServerToolResultStepResultType
}

func CreateMCPServerToolResultStepResultArrayOfFunctionResultSubcontent(arrayOfFunctionResultSubcontent []FunctionResultSubcontent) MCPServerToolResultStepResult {
	typ := MCPServerToolResultStepResultTypeArrayOfFunctionResultSubcontent

	return MCPServerToolResultStepResult{
		ArrayOfFunctionResultSubcontent: arrayOfFunctionResultSubcontent,
		Type:                            typ,
	}
}

func CreateMCPServerToolResultStepResultMapOfAny(mapOfAny map[string]any) MCPServerToolResultStepResult {
	typ := MCPServerToolResultStepResultTypeMapOfAny

	return MCPServerToolResultStepResult{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func CreateMCPServerToolResultStepResultStr(str string) MCPServerToolResultStepResult {
	typ := MCPServerToolResultStepResultTypeStr

	return MCPServerToolResultStepResult{
		Str:  &str,
		Type: typ,
	}
}

func CreateMCPServerToolResultStepResultUnknown(raw json.RawMessage) MCPServerToolResultStepResult {
	return MCPServerToolResultStepResult{
		UnknownRaw: raw,
		Type:       MCPServerToolResultStepResultTypeUnknown,
	}
}

func (u MCPServerToolResultStepResult) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u MCPServerToolResultStepResult) IsUnknown() bool {
	return u.Type == MCPServerToolResultStepResultTypeUnknown
}

func (u *MCPServerToolResultStepResult) UnmarshalJSON(data []byte) error {
	*u = MCPServerToolResultStepResult{}

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var arrayOfFunctionResultSubcontent []FunctionResultSubcontent = []FunctionResultSubcontent{}
	if err := utils.UnmarshalJSON(data, &arrayOfFunctionResultSubcontent, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MCPServerToolResultStepResultTypeArrayOfFunctionResultSubcontent,
			Value: arrayOfFunctionResultSubcontent,
		})
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MCPServerToolResultStepResultTypeMapOfAny,
			Value: mapOfAny,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MCPServerToolResultStepResultTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = MCPServerToolResultStepResultTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = MCPServerToolResultStepResultTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(MCPServerToolResultStepResultType)
	switch best.Type {
	case MCPServerToolResultStepResultTypeArrayOfFunctionResultSubcontent:
		u.ArrayOfFunctionResultSubcontent = best.Value.([]FunctionResultSubcontent)
		return nil
	case MCPServerToolResultStepResultTypeMapOfAny:
		u.MapOfAny = best.Value.(map[string]any)
		return nil
	case MCPServerToolResultStepResultTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = MCPServerToolResultStepResultTypeUnknown
	return nil
}

func (u MCPServerToolResultStepResult) MarshalJSON() ([]byte, error) {
	if u.ArrayOfFunctionResultSubcontent != nil {
		return utils.MarshalJSON(u.ArrayOfFunctionResultSubcontent, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type MCPServerToolResultStepResult: all fields are null")
}

// MCPServerToolResultStep - MCPServer tool result step.
type MCPServerToolResultStep struct {
	// Required. ID to match the ID from the function call block.
	CallID string `json:"call_id"`
	// Name of the tool which is called for this specific tool call.
	Name *string `json:"name,omitzero"`
	// Required. The output from the MCP server call. Can be simple text or rich content.
	Result MCPServerToolResultStepResult `json:"result"`
	// The name of the used MCP server.
	ServerName *string `json:"server_name,omitzero"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"mcp_server_tool_result" json:"type"`
}

func (m MCPServerToolResultStep) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MCPServerToolResultStep) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MCPServerToolResultStep) GetCallID() string {
	if m == nil {
		return ""
	}
	return m.CallID
}

func (m *MCPServerToolResultStep) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MCPServerToolResultStep) GetResult() MCPServerToolResultStepResult {
	if m == nil {
		return MCPServerToolResultStepResult{}
	}
	return m.Result
}

func (m *MCPServerToolResultStep) GetServerName() *string {
	if m == nil {
		return nil
	}
	return m.ServerName
}

func (m *MCPServerToolResultStep) GetType() string {
	return "mcp_server_tool_result"
}
