// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package interactions

import (
	"encoding/json"
	"errors"
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/sdk/sdkinternal/utils"
)

type StepType string

const (
	StepTypeCodeExecutionCall   StepType = "code_execution_call"
	StepTypeCodeExecutionResult StepType = "code_execution_result"
	StepTypeFileSearchCall      StepType = "file_search_call"
	StepTypeFileSearchResult    StepType = "file_search_result"
	StepTypeFunctionCall        StepType = "function_call"
	StepTypeFunctionResult      StepType = "function_result"
	StepTypeGoogleMapsCall      StepType = "google_maps_call"
	StepTypeGoogleMapsResult    StepType = "google_maps_result"
	StepTypeGoogleSearchCall    StepType = "google_search_call"
	StepTypeGoogleSearchResult  StepType = "google_search_result"
	StepTypeMcpServerToolCall   StepType = "mcp_server_tool_call"
	StepTypeMcpServerToolResult StepType = "mcp_server_tool_result"
	StepTypeModelOutput         StepType = "model_output"
	StepTypeProcessingCall      StepType = "processing_call"
	StepTypeProcessingResult    StepType = "processing_result"
	StepTypeRetrievalCall       StepType = "retrieval_call"
	StepTypeRetrievalResult     StepType = "retrieval_result"
	StepTypeThought             StepType = "thought"
	StepTypeURLContextCall      StepType = "url_context_call"
	StepTypeURLContextResult    StepType = "url_context_result"
	StepTypeUserInput           StepType = "user_input"
	StepTypeUnknown             StepType = "UNKNOWN"
)

// Step - A step in the interaction.
type Step struct {
	CodeExecutionCallStep   *CodeExecutionCallStep   `queryParam:"inline" union:"member"`
	CodeExecutionResultStep *CodeExecutionResultStep `queryParam:"inline" union:"member"`
	FileSearchCallStep      *FileSearchCallStep      `queryParam:"inline" union:"member"`
	FileSearchResultStep    *FileSearchResultStep    `queryParam:"inline" union:"member"`
	FunctionCallStep        *FunctionCallStep        `queryParam:"inline" union:"member"`
	FunctionResultStep      *FunctionResultStep      `queryParam:"inline" union:"member"`
	GoogleMapsCallStep      *GoogleMapsCallStep      `queryParam:"inline" union:"member"`
	GoogleMapsResultStep    *GoogleMapsResultStep    `queryParam:"inline" union:"member"`
	GoogleSearchCallStep    *GoogleSearchCallStep    `queryParam:"inline" union:"member"`
	GoogleSearchResultStep  *GoogleSearchResultStep  `queryParam:"inline" union:"member"`
	MCPServerToolCallStep   *MCPServerToolCallStep   `queryParam:"inline" union:"member"`
	MCPServerToolResultStep *MCPServerToolResultStep `queryParam:"inline" union:"member"`
	ModelOutputStep         *ModelOutputStep         `queryParam:"inline" union:"member"`
	ProcessingCallStep      *ProcessingCallStep      `queryParam:"inline" union:"member"`
	ProcessingResultStep    *ProcessingResultStep    `queryParam:"inline" union:"member"`
	RetrievalCallStep       *RetrievalCallStep       `queryParam:"inline" union:"member"`
	RetrievalResultStep     *RetrievalResultStep     `queryParam:"inline" union:"member"`
	ThoughtStep             *ThoughtStep             `queryParam:"inline" union:"member"`
	URLContextCallStep      *URLContextCallStep      `queryParam:"inline" union:"member"`
	URLContextResultStep    *URLContextResultStep    `queryParam:"inline" union:"member"`
	UserInputStep           *UserInputStep           `queryParam:"inline" union:"member"`
	UnknownRaw              json.RawMessage          `json:"-" union:"unknown"`

	Type StepType
}

func CreateStepCodeExecutionCall(codeExecutionCall CodeExecutionCallStep) Step {
	typ := StepTypeCodeExecutionCall

	return Step{
		CodeExecutionCallStep: &codeExecutionCall,
		Type:                  typ,
	}
}

func CreateStepCodeExecutionResult(codeExecutionResult CodeExecutionResultStep) Step {
	typ := StepTypeCodeExecutionResult

	return Step{
		CodeExecutionResultStep: &codeExecutionResult,
		Type:                    typ,
	}
}

func CreateStepFileSearchCall(fileSearchCall FileSearchCallStep) Step {
	typ := StepTypeFileSearchCall

	return Step{
		FileSearchCallStep: &fileSearchCall,
		Type:               typ,
	}
}

func CreateStepFileSearchResult(fileSearchResult FileSearchResultStep) Step {
	typ := StepTypeFileSearchResult

	return Step{
		FileSearchResultStep: &fileSearchResult,
		Type:                 typ,
	}
}

func CreateStepFunctionCall(functionCall FunctionCallStep) Step {
	typ := StepTypeFunctionCall

	return Step{
		FunctionCallStep: &functionCall,
		Type:             typ,
	}
}

func CreateStepFunctionResult(functionResult FunctionResultStep) Step {
	typ := StepTypeFunctionResult

	return Step{
		FunctionResultStep: &functionResult,
		Type:               typ,
	}
}

func CreateStepGoogleMapsCall(googleMapsCall GoogleMapsCallStep) Step {
	typ := StepTypeGoogleMapsCall

	return Step{
		GoogleMapsCallStep: &googleMapsCall,
		Type:               typ,
	}
}

func CreateStepGoogleMapsResult(googleMapsResult GoogleMapsResultStep) Step {
	typ := StepTypeGoogleMapsResult

	return Step{
		GoogleMapsResultStep: &googleMapsResult,
		Type:                 typ,
	}
}

func CreateStepGoogleSearchCall(googleSearchCall GoogleSearchCallStep) Step {
	typ := StepTypeGoogleSearchCall

	return Step{
		GoogleSearchCallStep: &googleSearchCall,
		Type:                 typ,
	}
}

func CreateStepGoogleSearchResult(googleSearchResult GoogleSearchResultStep) Step {
	typ := StepTypeGoogleSearchResult

	return Step{
		GoogleSearchResultStep: &googleSearchResult,
		Type:                   typ,
	}
}

func CreateStepMcpServerToolCall(mcpServerToolCall MCPServerToolCallStep) Step {
	typ := StepTypeMcpServerToolCall

	return Step{
		MCPServerToolCallStep: &mcpServerToolCall,
		Type:                  typ,
	}
}

func CreateStepMcpServerToolResult(mcpServerToolResult MCPServerToolResultStep) Step {
	typ := StepTypeMcpServerToolResult

	return Step{
		MCPServerToolResultStep: &mcpServerToolResult,
		Type:                    typ,
	}
}

func CreateStepModelOutput(modelOutput ModelOutputStep) Step {
	typ := StepTypeModelOutput

	return Step{
		ModelOutputStep: &modelOutput,
		Type:            typ,
	}
}

func CreateStepProcessingCall(processingCall ProcessingCallStep) Step {
	typ := StepTypeProcessingCall

	return Step{
		ProcessingCallStep: &processingCall,
		Type:               typ,
	}
}

func CreateStepProcessingResult(processingResult ProcessingResultStep) Step {
	typ := StepTypeProcessingResult

	return Step{
		ProcessingResultStep: &processingResult,
		Type:                 typ,
	}
}

func CreateStepRetrievalCall(retrievalCall RetrievalCallStep) Step {
	typ := StepTypeRetrievalCall

	return Step{
		RetrievalCallStep: &retrievalCall,
		Type:              typ,
	}
}

func CreateStepRetrievalResult(retrievalResult RetrievalResultStep) Step {
	typ := StepTypeRetrievalResult

	return Step{
		RetrievalResultStep: &retrievalResult,
		Type:                typ,
	}
}

func CreateStepThought(thought ThoughtStep) Step {
	typ := StepTypeThought

	return Step{
		ThoughtStep: &thought,
		Type:        typ,
	}
}

func CreateStepURLContextCall(urlContextCall URLContextCallStep) Step {
	typ := StepTypeURLContextCall

	return Step{
		URLContextCallStep: &urlContextCall,
		Type:               typ,
	}
}

func CreateStepURLContextResult(urlContextResult URLContextResultStep) Step {
	typ := StepTypeURLContextResult

	return Step{
		URLContextResultStep: &urlContextResult,
		Type:                 typ,
	}
}

func CreateStepUserInput(userInput UserInputStep) Step {
	typ := StepTypeUserInput

	return Step{
		UserInputStep: &userInput,
		Type:          typ,
	}
}

func CreateStepUnknown(raw json.RawMessage) Step {
	return Step{
		UnknownRaw: raw,
		Type:       StepTypeUnknown,
	}
}

func (u Step) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u Step) IsUnknown() bool {
	return u.Type == StepTypeUnknown
}

func (u *Step) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = Step{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = StepTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = StepTypeUnknown
		return nil
	}

	switch dis.Type {
	case "code_execution_call":
		codeExecutionCallStep := new(CodeExecutionCallStep)
		if err := utils.UnmarshalJSON(data, &codeExecutionCallStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == code_execution_call) type CodeExecutionCallStep within Step: %w", string(data), err)
		}

		u.CodeExecutionCallStep = codeExecutionCallStep
		u.Type = StepTypeCodeExecutionCall
		return nil
	case "code_execution_result":
		codeExecutionResultStep := new(CodeExecutionResultStep)
		if err := utils.UnmarshalJSON(data, &codeExecutionResultStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == code_execution_result) type CodeExecutionResultStep within Step: %w", string(data), err)
		}

		u.CodeExecutionResultStep = codeExecutionResultStep
		u.Type = StepTypeCodeExecutionResult
		return nil
	case "file_search_call":
		fileSearchCallStep := new(FileSearchCallStep)
		if err := utils.UnmarshalJSON(data, &fileSearchCallStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == file_search_call) type FileSearchCallStep within Step: %w", string(data), err)
		}

		u.FileSearchCallStep = fileSearchCallStep
		u.Type = StepTypeFileSearchCall
		return nil
	case "file_search_result":
		fileSearchResultStep := new(FileSearchResultStep)
		if err := utils.UnmarshalJSON(data, &fileSearchResultStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == file_search_result) type FileSearchResultStep within Step: %w", string(data), err)
		}

		u.FileSearchResultStep = fileSearchResultStep
		u.Type = StepTypeFileSearchResult
		return nil
	case "function_call":
		functionCallStep := new(FunctionCallStep)
		if err := utils.UnmarshalJSON(data, &functionCallStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == function_call) type FunctionCallStep within Step: %w", string(data), err)
		}

		u.FunctionCallStep = functionCallStep
		u.Type = StepTypeFunctionCall
		return nil
	case "function_result":
		functionResultStep := new(FunctionResultStep)
		if err := utils.UnmarshalJSON(data, &functionResultStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == function_result) type FunctionResultStep within Step: %w", string(data), err)
		}

		u.FunctionResultStep = functionResultStep
		u.Type = StepTypeFunctionResult
		return nil
	case "google_maps_call":
		googleMapsCallStep := new(GoogleMapsCallStep)
		if err := utils.UnmarshalJSON(data, &googleMapsCallStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == google_maps_call) type GoogleMapsCallStep within Step: %w", string(data), err)
		}

		u.GoogleMapsCallStep = googleMapsCallStep
		u.Type = StepTypeGoogleMapsCall
		return nil
	case "google_maps_result":
		googleMapsResultStep := new(GoogleMapsResultStep)
		if err := utils.UnmarshalJSON(data, &googleMapsResultStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == google_maps_result) type GoogleMapsResultStep within Step: %w", string(data), err)
		}

		u.GoogleMapsResultStep = googleMapsResultStep
		u.Type = StepTypeGoogleMapsResult
		return nil
	case "google_search_call":
		googleSearchCallStep := new(GoogleSearchCallStep)
		if err := utils.UnmarshalJSON(data, &googleSearchCallStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == google_search_call) type GoogleSearchCallStep within Step: %w", string(data), err)
		}

		u.GoogleSearchCallStep = googleSearchCallStep
		u.Type = StepTypeGoogleSearchCall
		return nil
	case "google_search_result":
		googleSearchResultStep := new(GoogleSearchResultStep)
		if err := utils.UnmarshalJSON(data, &googleSearchResultStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == google_search_result) type GoogleSearchResultStep within Step: %w", string(data), err)
		}

		u.GoogleSearchResultStep = googleSearchResultStep
		u.Type = StepTypeGoogleSearchResult
		return nil
	case "mcp_server_tool_call":
		mcpServerToolCallStep := new(MCPServerToolCallStep)
		if err := utils.UnmarshalJSON(data, &mcpServerToolCallStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == mcp_server_tool_call) type MCPServerToolCallStep within Step: %w", string(data), err)
		}

		u.MCPServerToolCallStep = mcpServerToolCallStep
		u.Type = StepTypeMcpServerToolCall
		return nil
	case "mcp_server_tool_result":
		mcpServerToolResultStep := new(MCPServerToolResultStep)
		if err := utils.UnmarshalJSON(data, &mcpServerToolResultStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == mcp_server_tool_result) type MCPServerToolResultStep within Step: %w", string(data), err)
		}

		u.MCPServerToolResultStep = mcpServerToolResultStep
		u.Type = StepTypeMcpServerToolResult
		return nil
	case "model_output":
		modelOutputStep := new(ModelOutputStep)
		if err := utils.UnmarshalJSON(data, &modelOutputStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == model_output) type ModelOutputStep within Step: %w", string(data), err)
		}

		u.ModelOutputStep = modelOutputStep
		u.Type = StepTypeModelOutput
		return nil
	case "processing_call":
		processingCallStep := new(ProcessingCallStep)
		if err := utils.UnmarshalJSON(data, &processingCallStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == processing_call) type ProcessingCallStep within Step: %w", string(data), err)
		}

		u.ProcessingCallStep = processingCallStep
		u.Type = StepTypeProcessingCall
		return nil
	case "processing_result":
		processingResultStep := new(ProcessingResultStep)
		if err := utils.UnmarshalJSON(data, &processingResultStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == processing_result) type ProcessingResultStep within Step: %w", string(data), err)
		}

		u.ProcessingResultStep = processingResultStep
		u.Type = StepTypeProcessingResult
		return nil
	case "retrieval_call":
		retrievalCallStep := new(RetrievalCallStep)
		if err := utils.UnmarshalJSON(data, &retrievalCallStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == retrieval_call) type RetrievalCallStep within Step: %w", string(data), err)
		}

		u.RetrievalCallStep = retrievalCallStep
		u.Type = StepTypeRetrievalCall
		return nil
	case "retrieval_result":
		retrievalResultStep := new(RetrievalResultStep)
		if err := utils.UnmarshalJSON(data, &retrievalResultStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == retrieval_result) type RetrievalResultStep within Step: %w", string(data), err)
		}

		u.RetrievalResultStep = retrievalResultStep
		u.Type = StepTypeRetrievalResult
		return nil
	case "thought":
		thoughtStep := new(ThoughtStep)
		if err := utils.UnmarshalJSON(data, &thoughtStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == thought) type ThoughtStep within Step: %w", string(data), err)
		}

		u.ThoughtStep = thoughtStep
		u.Type = StepTypeThought
		return nil
	case "url_context_call":
		urlContextCallStep := new(URLContextCallStep)
		if err := utils.UnmarshalJSON(data, &urlContextCallStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == url_context_call) type URLContextCallStep within Step: %w", string(data), err)
		}

		u.URLContextCallStep = urlContextCallStep
		u.Type = StepTypeURLContextCall
		return nil
	case "url_context_result":
		urlContextResultStep := new(URLContextResultStep)
		if err := utils.UnmarshalJSON(data, &urlContextResultStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == url_context_result) type URLContextResultStep within Step: %w", string(data), err)
		}

		u.URLContextResultStep = urlContextResultStep
		u.Type = StepTypeURLContextResult
		return nil
	case "user_input":
		userInputStep := new(UserInputStep)
		if err := utils.UnmarshalJSON(data, &userInputStep, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == user_input) type UserInputStep within Step: %w", string(data), err)
		}

		u.UserInputStep = userInputStep
		u.Type = StepTypeUserInput
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = StepTypeUnknown
		return nil
	}

}

func (u Step) MarshalJSON() ([]byte, error) {
	if u.CodeExecutionCallStep != nil {
		return utils.MarshalJSON(u.CodeExecutionCallStep, "", true)
	}

	if u.CodeExecutionResultStep != nil {
		return utils.MarshalJSON(u.CodeExecutionResultStep, "", true)
	}

	if u.FileSearchCallStep != nil {
		return utils.MarshalJSON(u.FileSearchCallStep, "", true)
	}

	if u.FileSearchResultStep != nil {
		return utils.MarshalJSON(u.FileSearchResultStep, "", true)
	}

	if u.FunctionCallStep != nil {
		return utils.MarshalJSON(u.FunctionCallStep, "", true)
	}

	if u.FunctionResultStep != nil {
		return utils.MarshalJSON(u.FunctionResultStep, "", true)
	}

	if u.GoogleMapsCallStep != nil {
		return utils.MarshalJSON(u.GoogleMapsCallStep, "", true)
	}

	if u.GoogleMapsResultStep != nil {
		return utils.MarshalJSON(u.GoogleMapsResultStep, "", true)
	}

	if u.GoogleSearchCallStep != nil {
		return utils.MarshalJSON(u.GoogleSearchCallStep, "", true)
	}

	if u.GoogleSearchResultStep != nil {
		return utils.MarshalJSON(u.GoogleSearchResultStep, "", true)
	}

	if u.MCPServerToolCallStep != nil {
		return utils.MarshalJSON(u.MCPServerToolCallStep, "", true)
	}

	if u.MCPServerToolResultStep != nil {
		return utils.MarshalJSON(u.MCPServerToolResultStep, "", true)
	}

	if u.ModelOutputStep != nil {
		return utils.MarshalJSON(u.ModelOutputStep, "", true)
	}

	if u.ProcessingCallStep != nil {
		return utils.MarshalJSON(u.ProcessingCallStep, "", true)
	}

	if u.ProcessingResultStep != nil {
		return utils.MarshalJSON(u.ProcessingResultStep, "", true)
	}

	if u.RetrievalCallStep != nil {
		return utils.MarshalJSON(u.RetrievalCallStep, "", true)
	}

	if u.RetrievalResultStep != nil {
		return utils.MarshalJSON(u.RetrievalResultStep, "", true)
	}

	if u.ThoughtStep != nil {
		return utils.MarshalJSON(u.ThoughtStep, "", true)
	}

	if u.URLContextCallStep != nil {
		return utils.MarshalJSON(u.URLContextCallStep, "", true)
	}

	if u.URLContextResultStep != nil {
		return utils.MarshalJSON(u.URLContextResultStep, "", true)
	}

	if u.UserInputStep != nil {
		return utils.MarshalJSON(u.UserInputStep, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type Step: all fields are null")
}
