// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package triggers

import (
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/client"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/interactive"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/operations"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

var runCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Required. Resource name of the trigger. [required]"},
}

// initRunCmd initializes the run command.
func initRunCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "run [id]",
		Short:   "Run a trigger immediately",
		Long:    "Runs a trigger immediately.",
		Example: "",
		Args:    flagutil.PositionalFlagArgs,
		RunE:    runRunCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "RunTrigger",
		},
	}
	flagutil.RegisterFlags(cmd, runCmdMeta)
	if err := flagutil.ValidateMeta[operations.RunTriggerRequest](runCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for run: %w", err)
	}
	if err := flagutil.DeclarePositionalFlag(cmd, "id", "Required. Resource name of the trigger. (or pass it as the [id] argument)", true); err != nil {
		return err
	}
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{Name: "id", Summary: "Required. Resource name of the trigger.", Required: true, SatisfiedBy: []string{"id"}},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for run: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runRunCmd executes the run command.
func runRunCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if err := flagutil.ResolvePositionalFlag(cmd, args); err != nil {
		return err
	}
	req, err := flagutil.BuildRequest[operations.RunTriggerRequest](cmd, runCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Triggers.Run(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
