// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"sync"
	"time"

	"github.com/google-gemini/gemini-api-cli/internal/config"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/components"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/retry"
	"github.com/google-gemini/gemini-api-cli/internal/sdk"
	"github.com/google-gemini/gemini-api-cli/internal/testclient"
	"github.com/spf13/cobra"
)

// NewClient creates a new SDK client configured from command flags and environment.
// It handles global security, server URL/selection override, global parameters,
// retry configuration, timeout, and test client injection.
// Empty allowedSecurityFields accepts every global security alternative.
func NewClient(cmd *cobra.Command, allowedSecurityFields ...string) (*sdk.GeminiAPI, error) {
	var sdkOpts []sdk.SDKOption
	sdkOpts = append(sdkOpts, sdk.WithSecurity(buildGlobalSecurity(cmd, allowedSecurityFields)))
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		if err := flagutil.ValidateServerURL(serverURL); err != nil {
			return nil, err
		}
	}
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, sdk.WithServerURL(serverURL))
	}

	sdkOpts = append(sdkOpts, buildGlobalOptions(cmd)...)

	// Timeout (always available)
	if timeoutStr := resolveStringFlag(cmd, "timeout"); timeoutStr != "" {
		timeout, err := time.ParseDuration(timeoutStr)
		if err != nil {
			return nil, flagutil.WithCLIValidation(fmt.Errorf("invalid --timeout value %q: %w", timeoutStr, err))
		}
		sdkOpts = append(sdkOpts, sdk.WithTimeout(timeout))
	} // Retry configuration
	retryConfig, err := buildRetryConfig(cmd)
	if err != nil {
		return nil, err
	}
	if retryConfig != nil {
		sdkOpts = append(sdkOpts, sdk.WithRetryConfig(*retryConfig))
	}

	// Diagnostics and test client composition.
	// Order: test client (innermost) → diagnostics wrapper (outermost).
	var httpClient HTTPClient = &http.Client{Transport: newPhaseBoundedTransport(cmd)}
	if testClient := testclient.NewTestHTTPClient(); testClient != nil {
		httpClient = testClient
	}
	httpClient = WrapClientForDiagnostics(cmd, httpClient)
	sdkOpts = append(sdkOpts, sdk.WithClient(httpClient))
	return sdk.New(sdkOpts...), nil
}

func newPhaseBoundedTransport(cmd *cobra.Command) http.RoundTripper {
	var phase time.Duration
	if s := resolveStringFlag(cmd, "timeout"); s != "" {
		d, err := time.ParseDuration(s)
		if err != nil || d <= 0 {
			return nil
		}
		phase = d
	}
	if phase <= 0 {
		return nil
	}
	if cached, ok := phaseBoundedTransports.Load(phase); ok {
		return cached.(*http.Transport)
	}
	transport, ok := http.DefaultTransport.(*http.Transport)
	if !ok {
		return nil
	}
	bounded := transport.Clone()
	// http.DefaultTransport dials with a 30s timeout and a 10s TLS handshake timeout.
	if phase < 30*time.Second {
		bounded.DialContext = (&net.Dialer{Timeout: phase, KeepAlive: 30 * time.Second}).DialContext
	}
	if phase < bounded.TLSHandshakeTimeout {
		bounded.TLSHandshakeTimeout = phase
	}
	bounded.ResponseHeaderTimeout = phase
	actual, _ := phaseBoundedTransports.LoadOrStore(phase, bounded)
	return actual.(*http.Transport)
}

var phaseBoundedTransports sync.Map

// resolveStringFlag reads a string flag with priority: flag > env > config.
func resolveStringFlag(cmd *cobra.Command, name string) string {
	if val, changed := flagutil.GetStringFlag(cmd, name); changed && val != "" {
		return val
	}
	return config.GetString(name)
}

// buildGlobalSecurity reads security credentials with priority: flag > env var > keyring > config.
func buildGlobalSecurity(cmd *cobra.Command, allowedSecurityFields []string) components.Security {
	// Resolve request credentials: flag > env var > keyring > config file (keyring skipped for dry-run)
	var (
		apiKey      string
		accessToken string
	)
	credentialSources := map[string]string{}
	apiKey, credentialSources["api-key"] = config.ResolveRequestSecurityCredential(cmd, "api-key")
	accessToken, credentialSources["access-token"] = config.ResolveRequestSecurityCredential(cmd, "access-token")
	globalSecurity := components.Security{}
	// Rank the alternatives by how explicitly the caller supplied them
	// (flag > env > keyring > config; complete before partial at the same
	// tier) and send exactly one: an explicit credential picks its scheme
	// regardless of the declared order.
	credentialCandidates := []config.CredentialCandidate{
		{Field: "APIKey", Complete: apiKey != "", Sources: []string{credentialSources["api-key"]}},
		{Field: "AccessToken", Complete: accessToken != "", Sources: []string{credentialSources["access-token"]}},
	}
	switch config.PickCredential(credentialCandidates, allowedSecurityFields) {
	case 0:
		globalSecurity.APIKey = &apiKey
	case 1:
		globalSecurity.AccessToken = &accessToken
	}
	return globalSecurity
}

// buildGlobalOptions reads global parameter flags and returns SDK options.
// Priority: flag > env var > config file.
func buildGlobalOptions(cmd *cobra.Command) []sdk.SDKOption {
	var opts []sdk.SDKOption
	if flagutil.FlagChanged(cmd, "api-version") {
		val, _ := flagutil.GetStringFlag(cmd, "api-version")
		opts = append(opts, sdk.WithAPIVersion(val))
	} else if val := config.GetString("api-version"); val != "" {
		opts = append(opts, sdk.WithAPIVersion(val))
	} else {
		val, _ := flagutil.GetStringFlag(cmd, "api-version")
		opts = append(opts, sdk.WithAPIVersion(val))
	}
	if flagutil.FlagChanged(cmd, "api-revision") {
		val, _ := flagutil.GetStringFlag(cmd, "api-revision")
		opts = append(opts, sdk.WithAPIRevision(val))
	} else if val := config.GetString("api-revision"); val != "" {
		opts = append(opts, sdk.WithAPIRevision(val))
	}
	if flagutil.FlagChanged(cmd, "user-project") {
		val, _ := flagutil.GetStringFlag(cmd, "user-project")
		opts = append(opts, sdk.WithUserProject(val))
	} else if val := config.GetString("user-project"); val != "" {
		opts = append(opts, sdk.WithUserProject(val))
	}
	return opts
}

// buildRetryConfig reads retry flags and constructs a retry configuration.
// Returns (nil, nil) if no retry flags were set (use spec/SDK defaults).
// Returns non-nil error for invalid flag values (malformed JSON, bad duration).
func buildRetryConfig(cmd *cobra.Command) (*retry.Config, error) {
	// --no-retries: highest precedence
	if noRetries, changed := flagutil.GetBoolFlag(cmd, "no-retries"); changed {
		if noRetries {
			return &retry.Config{Strategy: ""}, nil
		}
		// Explicit --no-retries=false: skip config fallback, proceed to other flags
	} else if val := config.GetString("no-retries"); val == "true" {
		return &retry.Config{Strategy: ""}, nil
	}

	// --retry-config: full JSON override
	if configJSON, changed := flagutil.GetStringFlag(cmd, "retry-config"); changed && configJSON != "" {
		var cfg retry.Config
		if err := json.Unmarshal([]byte(configJSON), &cfg); err != nil {
			return nil, flagutil.WithCLIValidation(fmt.Errorf("invalid --retry-config JSON: %w", err))
		}
		return &cfg, nil
	}
	if configJSON := config.GetString("retry-config"); configJSON != "" {
		var cfg retry.Config
		if err := json.Unmarshal([]byte(configJSON), &cfg); err != nil {
			return nil, flagutil.WithCLIValidation(fmt.Errorf("invalid retry-config in config file: %w", err))
		}
		return &cfg, nil
	}

	// Individual flags: build fresh config with CLI defaults, override specific fields.
	// Note: this REPLACES the spec-level retry config entirely (the SDK takes a
	// complete retry.Config, not a partial merge). Use --retry-config JSON for
	// exact control over all parameters.
	var hasOverride bool
	retryConfig := retry.Config{
		Strategy: "backoff",
		Backoff: &retry.BackoffStrategy{
			InitialInterval: 500,
			MaxInterval:     10000,
			Exponent:        1.5,
			MaxElapsedTime:  30000,
		},
	}

	if maxElapsed := resolveStringFlag(cmd, "retry-max-elapsed-time"); maxElapsed != "" {
		dur, err := time.ParseDuration(maxElapsed)
		if err != nil {
			return nil, flagutil.WithCLIValidation(fmt.Errorf("invalid --retry-max-elapsed-time value %q: %w", maxElapsed, err))
		}
		retryConfig.Backoff.MaxElapsedTime = int(dur.Milliseconds())
		hasOverride = true
	}
	if retryConn, changed := flagutil.GetBoolFlag(cmd, "retry-connection-errors"); changed {
		retryConfig.RetryConnectionErrors = retryConn
		hasOverride = true
	} else if val := config.GetString("retry-connection-errors"); val == "true" {
		retryConfig.RetryConnectionErrors = true
		hasOverride = true
	}

	if hasOverride {
		return &retryConfig, nil
	}
	return nil, nil
}
