// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package output

// Generated from the x-speakeasy-cli-errors document extension.

// errorProbes lists this build's reason carriers in classification order:
// the primary carrier (the declared reasonPointer, default $.reason) first,
// then each declared probe.
var errorProbes = []errorProbe{
	{
		// $.details[*].reason
		segments: []reasonCarrierSegment{
			{field: "details"},
			{isWild: true},
			{field: "reason"},
		},
		rules: map[string]errorRule{
			"ACCESS_TOKEN_EXPIRED": {
				Type: ErrorType("authentication_error"),
				Hints: []string{
					"The OAuth access token has expired. Refresh it and pass the new value with --access-token (or use an API key via GEMINI_API_KEY)",
				},
			},
			"ACCESS_TOKEN_SCOPE_INSUFFICIENT": {
				Type: ErrorType("authorization_error"),
				Hints: []string{
					"The access token lacks the scope this call needs (https://www.googleapis.com/auth/generative-language). Re-authorize with that scope, or use an API key via GEMINI_API_KEY",
				},
			},
			"ACCESS_TOKEN_TYPE_UNSUPPORTED": {
				Type: ErrorType("authentication_error"),
				Hints: []string{
					"This token type is not accepted here. Use an API key (GEMINI_API_KEY) or a bearer OAuth access token via --access-token",
				},
			},
			"API_KEY_HTTP_REFERRER_BLOCKED": {
				Type: ErrorType("authorization_error"),
				Hints: []string{
					"This API key only accepts requests from allow-listed HTTP referrers, which a CLI does not send. Use a key without referrer restrictions",
				},
			},
			"API_KEY_INVALID": {
				Type: ErrorType("authentication_error"),
				Hints: []string{
					"The API key was rejected. Create a key at https://aistudio.google.com/apikey, then export GEMINI_API_KEY=<key> (or run \"gemini-api configure\" to store it)",
					"Run \"gemini-api whoami\" to see which credential is being sent",
				},
			},
			"API_KEY_IP_ADDRESS_BLOCKED": {
				Type: ErrorType("authorization_error"),
				Hints: []string{
					"This API key only accepts requests from allow-listed IP addresses. Add this machine's address to the key's restrictions or use a key without IP restrictions",
				},
			},
			"API_KEY_MISSING": {
				Type: ErrorType("authentication_error"),
				Hints: []string{
					"No API key was sent. Export GEMINI_API_KEY=<key> (create one at https://aistudio.google.com/apikey) or run \"gemini-api configure\"",
				},
			},
			"API_KEY_SERVICE_BLOCKED": {
				Type: ErrorType("authorization_error"),
				Hints: []string{
					"This API key is restricted from calling the Gemini API. Edit the key's API restrictions in Google AI Studio / Cloud Console, or use an unrestricted key",
				},
			},
			"BILLING_DISABLED": {
				Type: ErrorType("billing_disabled"),
				Hints: []string{
					"Billing is disabled for the project that owns this key (this is not a credential problem). Enable billing on the project or use a key from a project with billing enabled; the free tier may not be available in your region",
				},
			},
			"CONSUMER_SUSPENDED": {
				Type: ErrorType("authorization_error"),
				Hints: []string{
					"The Google Cloud project behind this key is suspended (this is not a credential problem). Check the project status in the Cloud Console",
				},
			},
			"CREDENTIALS_MISSING": {
				Type: ErrorType("authentication_error"),
				Hints: []string{
					"No credential was sent. Export GEMINI_API_KEY=<key> (create one at https://aistudio.google.com/apikey) or run \"gemini-api configure\"",
				},
			},
			"QUOTA_EXCEEDED": {
				Type: ErrorType("rate_limit_error"),
				Hints: []string{
					"Quota exhausted for this model or project. Wait for the quota window to reset, request a higher tier at https://ai.google.dev/gemini-api/docs/rate-limits, or pick another model with --model",
				},
			},
			"RATE_LIMIT_EXCEEDED": {
				Type: ErrorType("rate_limit_error"),
				Hints: []string{
					"Rate limit hit for this model. Back off and retry, or pick a lighter model with --model; limits per model are at https://ai.google.dev/gemini-api/docs/rate-limits",
				},
			},
			"RESOURCE_EXHAUSTED": {
				Type: ErrorType("rate_limit_error"),
				Hints: []string{
					"Quota exhausted. Wait and retry with backoff, or pick another model with --model; limits are at https://ai.google.dev/gemini-api/docs/rate-limits",
				},
			},
			"SERVICE_DISABLED": {
				Type: ErrorType("service_disabled"),
				Hints: []string{
					"The Generative Language API is disabled for the project that owns this key (this is not a credential problem). Enable it at https://console.developers.google.com/apis/api/generativelanguage.googleapis.com/overview?project=<project>, then retry after a few minutes",
				},
			},
			"USER_PROJECT_DENIED": {
				Type: ErrorType("authorization_error"),
				Hints: []string{
					"The caller may not bill the quota project named by --user-project / GEMINI_USER_PROJECT. Use a project you have serviceusage.services.use on, or drop the flag",
				},
			},
		},
		promote: true,
	},
	{
		// $.status
		segments: []reasonCarrierSegment{
			{field: "status"},
		},
		rules: map[string]errorRule{
			"NOT_FOUND": {
				Type: ErrorType("not_found"),
			},
			"PERMISSION_DENIED": {
				Type: ErrorType("authorization_error"),
			},
			"RESOURCE_EXHAUSTED": {
				Type: ErrorType("rate_limit_error"),
			},
			"UNAUTHENTICATED": {
				Type: ErrorType("authentication_error"),
			},
		},
		promote: true,
	},
}

// runtimeReasonHints replaces the generated guidance for the runtime-owned
// CLI_* reasons the local runtime emits.
var runtimeReasonHints = map[string][]string{}

var declaredTypeHints = map[ErrorType][]string{
	ErrorType("authentication_error"): {
		"Set GEMINI_API_KEY to a valid key from https://aistudio.google.com/apikey, or run \"gemini-api configure\" to store one",
		"Run \"gemini-api whoami\" to see which credential is being sent",
	},
	ErrorType("billing_disabled"): {
		"Billing is disabled for the calling account or project — enable billing (this is not a credential problem)",
	},
	ErrorType("not_found"): {
		"Check the resource name (models are \"gemini-…\"; files are \"files/<id>\"; agents and interactions have distinct ids). \"gemini-api models\" lists the curated models",
	},
	ErrorType("service_disabled"): {
		"The API service is disabled for the calling account or project — enable it before retrying (this is not a credential problem)",
	},
}
