// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package output

import (
	"encoding/json"
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/itchyny/gojq"
)

// ApplyJqFilter applies a jq expression to the given content and returns the results.
// The content is first marshaled to JSON and back to ensure a clean interface{} structure,
// then the jq expression is evaluated against it.
func ApplyJqFilter(content interface{}, expression string) ([]interface{}, error) {
	// Marshal to JSON and back to get a clean JSON-compatible structure.
	// SDK types have custom marshal methods so we need to go through JSON
	// to get plain maps/slices/primitives that gojq can process.
	jsonData, err := json.Marshal(content)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal for jq: %w", err)
	}

	var data interface{}
	if err := json.Unmarshal(jsonData, &data); err != nil {
		return nil, fmt.Errorf("failed to prepare data for jq: %w", err)
	}

	query, err := gojq.Parse(expression)
	if err != nil {
		return nil, flagutil.WithCLIValidation(fmt.Errorf("invalid jq expression %q: %w", expression, err))
	}

	var results []interface{}
	iter := query.Run(data)
	for {
		v, ok := iter.Next()
		if !ok {
			break
		}
		if err, isErr := v.(error); isErr {
			return nil, fmt.Errorf("jq error: %w", err)
		}
		results = append(results, v)
	}

	return results, nil
}
