// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

// Package output — incremental item output for pagination and streaming.
// This file is generated when at least one operation uses pagination or streaming.
package output

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
)

// outputOneItem outputs a single item in the appropriate streaming format.
func outputOneItem(out io.Writer, item interface{}, format, jqExpr string, colorize, jqRaw, first bool) error {
	if jqExpr != "" {
		results, err := ApplyJqFilter(item, jqExpr)
		if err != nil {
			return err
		}
		for _, r := range results {
			if s, ok := r.(string); ok && jqRaw {
				if _, err := fmt.Fprintln(out, s); err != nil {
					return err
				}
				continue
			}
			data, err := json.Marshal(r)
			if err != nil {
				return err
			}
			printJSON(out, data, colorize)
		}
		return nil
	}

	switch format {
	case "json":
		// NDJSON: one compact JSON object per line
		data, err := marshalJSON(item)
		if err != nil {
			return err
		}
		var compacted bytes.Buffer
		if err := json.Compact(&compacted, data); err != nil {
			// Fallback: output as-is
			printJSON(out, data, colorize)
			return nil
		}
		outBytes := compacted.Bytes()
		printJSON(out, outBytes, colorize)
	case "yaml":
		if !first {
			fmt.Fprintln(out, "---")
		}
		data, err := marshalYAML(item)
		if err != nil {
			return err
		}
		fmt.Fprint(out, string(data))
	case "toon":
		toonStr, err := encodeTOON(item)
		if err != nil {
			return err
		}
		if !first {
			fmt.Fprintln(out)
		}
		fmt.Fprint(out, toonStr)
	default: // "pretty"
		if !first {
			fmt.Fprintln(out) // blank line between items
		}
		if err := prettyPrint(out, item, colorize); err != nil {
			return err
		}
	}
	return nil
}
