// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

// Package clierrors defines the generated CLI's process-exit contract.
package clierrors

import "errors"

const (
	ExitOK      = 0
	ExitRuntime = 1
	ExitUsage   = 2
	ExitAuth    = 3
)

const HelpFooter = "Exit codes: 0 ok · 1 runtime · 2 usage · 3 authentication/authorization"

type ExitCoder interface {
	ExitCode() int
}

type CodedError struct {
	code int
	err  error
}

func (e *CodedError) Error() string { return e.err.Error() }

func (e *CodedError) Unwrap() error { return e.err }

func (e *CodedError) ExitCode() int { return e.code }

func normalizeCode(code int) int {
	switch code {
	case ExitRuntime, ExitUsage, ExitAuth:
		return code
	default:
		return ExitRuntime
	}
}

func WithExitCode(err error, code int) error {
	if err == nil {
		return nil
	}
	code = normalizeCode(code)
	if coded, ok := err.(ExitCoder); ok && normalizeCode(coded.ExitCode()) == code {
		return err
	}
	return &CodedError{code: code, err: err}
}

func ExitCode(err error) int {
	if err == nil {
		return ExitOK
	}
	var coded ExitCoder
	if errors.As(err, &coded) {
		return normalizeCode(coded.ExitCode())
	}
	return ExitRuntime
}

func ErrorTypeExitCode(errorType string) int {
	switch errorType {
	case "authentication_error", "authorization_error":
		return ExitAuth
	case "validation_error":
		return ExitUsage
	default:
		return ExitRuntime
	}
}

func CLIReasonExitCode(reason string) int {
	switch reason {
	case "CLI_AUTHENTICATION":
		return ExitAuth
	case "CLI_VALIDATION":
		return ExitUsage
	default:
		return ExitRuntime
	}
}
