// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agent

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/google-gemini/gemini-api-cli/internal/client"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/interactive"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitIntentMusic(parent *cobra.Command) error {
	cmd := &cobra.Command{
		Use:     "music [prompt]",
		Short:   "Music generation (lyria-3-pro-preview)",
		Long:    "Generate music via the Interactions API (audio response\nmodality).\n\nArguments:\n  <prompt>  Music prompt",
		Example: "  gemini-api music \"upbeat synthwave with a driving bassline\"",
		Args:    cobra.ArbitraryArgs,
		RunE:    runIntentMusicCmd,
		Annotations: map[string]string{
			"speakeasy_operation":            "CreateInteraction",
			flagutil.AnnotationWholeBodyFlag: "body",
			"speakeasy_strict_body_keys":     "true",
			"speakeasy_help_defaults":        "model lyria-3-pro-preview · output ./gemini-music-{timestamp}-{rand}.{ext}",
			"speakeasy_help_learn":           "https://ai.google.dev/gemini-api/docs/music-generation",
			"speakeasy_help_escalate":        "full request control via gemini-api agent run",
			"speakeasy_artifact":             "{\"pointer\":[{\"field\":\"steps\"},{\"wild\":true},{\"field\":\"content\"},{\"wild\":true}],\"kind\":\"audio\",\"defaultPath\":\"gemini-music-{timestamp}-{rand}.{ext}\"}",
		},
	}
	flagutil.RegisterFlags(cmd, runCmdMeta)
	flagutil.SetMetaPromptOptional(cmd, runCmdMeta, false)
	flagutil.ClearBodyRequirements(cmd, runCmdMeta, "Body")
	cmd.Flags().String("body", "", "Request body as JSON (advanced; replaces intent arguments). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	if err := flagutil.AnnotateBodyFields(cmd, runCmdMeta, "Body", "body", "body-param"); err != nil {
		return fmt.Errorf("annotate body fields for intent music: %w", err)
	}
	_ = flagutil.MarkBodyFlag(cmd, "body-param")
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	cmd.Flags().StringP("model", "m", "", "Override the music model (e.g. gemini-2.5-flash, gemini-2.5-pro, gemma-4-26b-a4b-it, gemma-4-31b-it, ...)")
	_ = flagutil.AnnotatePromptFlag(cmd, "model", flagutil.PromptFlagSpec{
		Required: false,
		Kind:     "string",
		Order:    0,
		// A supplied whole body carries this flag's bound key (and the
		// backing operation flag supplies it directly): no prompt then.
		BodySources: []string{"body", "body-param"},
	})
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{
			Name: "prompt", Summary: "Music prompt",
			Required: true, Variadic: true,
			BodyKey:     "input",
			SatisfiedBy: []string{"body", "body-param"},
		},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for intent music: %w", err)
	}
	cmd.Flags().String("out", "", "Write the audio to this file (or into this directory). Default: ./gemini-music-{timestamp}-{rand}.{ext}")
	_ = flagutil.AnnotatePromptFlag(cmd, "out", flagutil.PromptFlagSpec{
		PromptDirect: true,
		Label:        "Output file",
		Kind:         "string",
	})
	cmd.Flags().Bool("raw-response", false, "Print the raw API response instead of writing the audio to a file")
	for _, sibling := range parent.Commands() {
		if sibling.Name() == cmd.Name() || sibling.HasAlias(cmd.Name()) {
			return fmt.Errorf("intent command %q collides with the name or alias of an existing %q command; rename the declared command", "music", sibling.Name())
		}
	}
	parent.AddCommand(cmd)
	return nil
}

var intentMusicPreset = flagutil.PresetMerge{
	Command: "music",
	Variant: "ModelInteraction",
	Preset:  "{\"model\":\"lyria-3-pro-preview\",\"response_format\":{\"type\":\"audio\"},\"stream\":false}",
	Foreign: []string{"agent"},
	Escape:  "gemini-api agent run",
}

func runIntentMusicCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "CreateInteraction")
	}
	if flagutil.FlagChanged(cmd, "raw-response") && flagutil.FlagChanged(cmd, "out") {
		return flagutil.WithCLIValidation(fmt.Errorf("--raw-response prints the raw API response and cannot be combined with --out"))
	}
	bodySurfaces := []string{"body", "body-param"}
	for _, surface := range bodySurfaces {
		if flagutil.FlagChanged(cmd, surface) {
			if err := flagutil.ResolveBodyFlag(cmd, surface); err != nil {
				return err
			}
		}
	}
	suppliedBodyFlag := ""
	if flagutil.FlagChanged(cmd, "body-param") {
		suppliedBodyFlag = "body-param"
	}
	if flagutil.FlagChanged(cmd, "body") {
		suppliedBodyFlag = "body"
	}
	bodySupplied := suppliedBodyFlag != ""
	if !bodySupplied {
		attached, err := flagutil.AttachStdinBody(cmd, "body")
		if err != nil {
			return err
		}
		bodySupplied = attached
	}
	if hint := flagutil.SpacedBoolValueHint(cmd, args); hint != "" && !client.IsJSONDryRun(cmd) && !output.IsMachineMode(cmd) {
		fmt.Fprintln(cmd.ErrOrStderr(), hint)
	}
	if bodySupplied {
		if len(args) > 0 {
			if err := flagutil.MergeInputIntoBody(cmd, suppliedBodyFlag, "input", "the <prompt> argument", strings.Join(args, " ")); err != nil {
				return flagutil.WithCLIValidation(err)
			}
		}
		if flagutil.FlagChanged(cmd, "model") {
			v, _ := flagutil.GetStringFlag(cmd, "model")
			if err := flagutil.MergeInputIntoBody(cmd, suppliedBodyFlag, "model", "--model", v); err != nil {
				return flagutil.WithCLIValidation(err)
			}
		}
	}
	if len(args) == 0 && !bodySupplied && !flagutil.FlagChanged(cmd, "body") && !flagutil.FlagChanged(cmd, "body-param") && !flagutil.FlagChanged(cmd, "model") {
		return output.UsageHelpError(cmd, fmt.Errorf("%s", "missing required argument <prompt> (or pass a full request with --body)"))
	}
	if !bodySupplied {
		body := map[string]any{}
		if err := json.Unmarshal([]byte(intentMusicPreset.Preset), &body); err != nil {
			return err
		}
		if len(args) == 0 {
			return flagutil.WithCLIValidation(fmt.Errorf("missing required argument (or pass a full request with --body)"))
		}
		if len(args) > 0 {
			body["input"] = strings.Join(args, " ")
		}
		if flagutil.FlagChanged(cmd, "model") {
			v, _ := flagutil.GetStringFlag(cmd, "model")
			body["model"] = v
		}
		encoded, err := json.Marshal(body)
		if err != nil {
			return err
		}
		if err := cmd.Flags().Set("body", string(encoded)); err != nil {
			return err
		}
	} else {
		for _, surface := range bodySurfaces {
			if !flagutil.FlagChanged(cmd, surface) {
				continue
			}
			raw, _ := flagutil.GetStringFlag(cmd, surface)
			merged, err := flagutil.MergePresetBody(raw, intentMusicPreset)
			if err != nil {
				return err
			}
			if err := cmd.Flags().Set(surface, merged); err != nil {
				return err
			}
		}
	}
	return runRunCmd(cmd, nil)
}
