// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/google-gemini/gemini-api-cli/internal/client"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/interactive"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/operations"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitIntentVideo(parent *cobra.Command) error {
	cmd := &cobra.Command{
		Use:     "video [prompt]",
		Short:   "Generate & edit video conversationally (gemini-omni-1.1-flash)",
		Long:    "Generate video via the Interactions API (video response\nmodality). The interaction runs in the background: the CLI\npolls \"agent status\" with backoff until it completes, writes\nthe video to a file, and prints the file path; --async returns\nthe interaction ID immediately instead (resume with\n\"gemini-api video --resume <id>\"). A requires_action result\nis printed as-is. Use --out to choose the file (or a\ndirectory), --raw-response to see the API response instead.\n\nArguments:\n  <prompt>  Video prompt",
		Example: "  gemini-api video \"a timelapse of a city at night\" --async\n  gemini-api video \"a timelapse of a city at night\"",
		Args:    cobra.ArbitraryArgs,
		RunE:    runIntentVideoCmd,
		Annotations: map[string]string{
			"speakeasy_operation":            "CreateInteraction",
			flagutil.AnnotationWholeBodyFlag: "body",
			"speakeasy_strict_body_keys":     "true",
			"speakeasy_help_defaults":        "model gemini-omni-1.1-flash · polls until done, writes ./gemini-video-<ts>.mp4 (--async returns the interaction ID)",
			"speakeasy_help_learn":           "https://ai.google.dev/gemini-api/docs/video",
			"speakeasy_help_escalate":        "full request control via gemini-api agent run",
			"speakeasy_artifact":             "{\"pointer\":[{\"field\":\"steps\"},{\"wild\":true},{\"field\":\"content\"},{\"wild\":true}],\"kind\":\"video\",\"defaultPath\":\"gemini-video-{timestamp}-{rand}.{ext}\"}",
			"speakeasy_async":                "{\"idPointer\":\"/id\",\"statePointer\":\"/status\",\"states\":{\"budget_exceeded\":\"failure\",\"cancelled\":\"failure\",\"completed\":\"success\",\"failed\":\"failure\",\"in_progress\":\"pending\",\"incomplete\":\"failure\",\"queued\":\"pending\",\"requires_action\":\"handoff\"},\"interval\":\"5s\",\"backoff\":1.5,\"maxInterval\":\"30s\",\"timeout\":\"15m\",\"command\":\"video\",\"resume\":\"gemini-api video --resume\",\"parameterIn\":\"path\",\"parameterName\":\"interactionsId\",\"params\":[{\"in\":\"query\",\"name\":\"stream\",\"value\":false}]}",
		},
	}
	intentMeta := flagutil.NonBodyMeta(runCmdMeta, "Body")
	flagutil.RegisterFlags(cmd, intentMeta)
	flagutil.SetMetaPromptOptional(cmd, intentMeta, false)
	cmd.Flags().String("body", "", "Request body as JSON (advanced; merges with intent inputs, rejecting duplicate keys). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	cmd.Flags().StringP("model", "m", "", "Override the video model (e.g. gemini-omni-flash-preview, default: gemini-omni-1.1-flash)")
	flagutil.MarkRequestInput(cmd, "model")
	_ = flagutil.AnnotatePromptFlag(cmd, "model", flagutil.PromptFlagSpec{
		Required: false,
		Kind:     "string",
		Order:    0,

		BodySources: []string{"body"},
	})
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{
			Name: "prompt", Summary: "Video prompt",
			Required: true, Variadic: true,
			BodyKey:     "input",
			SatisfiedBy: []string{"body"},
		},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for intent video: %w", err)
	}
	cmd.Flags().String("out", "", "Write the video to this file (or into this directory). Default: ./gemini-video-{timestamp}-{rand}.{ext}")
	_ = flagutil.AnnotatePromptFlag(cmd, "out", flagutil.PromptFlagSpec{
		PromptDirect: true,
		Label:        "Output file",
		Kind:         "string",
	})
	cmd.Flags().Bool("raw-response", false, "Print the raw API response instead of writing the video to a file")
	cmd.Flags().String("resume", "", "Resume polling an existing operation by ID instead of creating one")
	_ = flagutil.AnnotatePromptFlag(cmd, "resume", flagutil.PromptFlagSpec{Kind: "string"})
	cmd.Flags().Bool("async", false, "Return the operation handle without waiting for a terminal response")
	cmd.Flags().String("poll-interval", "", "Override the initial polling interval (positive Go duration, for example 500ms or 2s)")
	cmd.Flags().String("poll-timeout", "", "Override the overall polling deadline (positive Go duration, at least the effective poll interval)")
	_ = flagutil.AnnotatePromptFlag(cmd, "async", flagutil.PromptFlagSpec{Kind: "bool"})
	_ = flagutil.AnnotatePromptFlag(cmd, "poll-interval", flagutil.PromptFlagSpec{Kind: "string"})
	_ = flagutil.AnnotatePromptFlag(cmd, "poll-timeout", flagutil.PromptFlagSpec{Kind: "string"})
	for _, sibling := range parent.Commands() {
		if sibling.Name() == cmd.Name() || sibling.HasAlias(cmd.Name()) {
			return fmt.Errorf("intent command %q collides with the name or alias of an existing %q command; rename the declared command", "video", sibling.Name())
		}
	}
	parent.AddCommand(cmd)
	return nil
}

var intentVideoPreset = flagutil.PresetMerge{
	Command: "video",
	Variant: "ModelInteraction",
	Preset:  "{\"background\":true,\"model\":\"gemini-omni-1.1-flash\",\"response_format\":{\"type\":\"video\"},\"stream\":false}",
	Foreign: []string{"agent"},
	Nested: map[string]flagutil.PresetMergePoint{
		"/response_format": {Key: "type", Values: []string{"\"video\""}},
	},
	Escape: "gemini-api agent run",
}

func runIntentVideoCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "CreateInteraction")
	}
	if flagutil.FlagChanged(cmd, "raw-response") && flagutil.FlagChanged(cmd, "out") {
		return flagutil.WithCLIValidation(fmt.Errorf("--raw-response prints the raw API response and cannot be combined with --out"))
	}
	if flagutil.IsAsyncResume(cmd) {
		if err := output.ValidateAsyncResume(cmd, args); err != nil {
			return err
		}
		id, _ := flagutil.GetStringFlag(cmd, "resume")
		return output.ResumeAsync(cmd, id, newPollIntentVideo)
	}
	bodySurfaces := []string{"body"}
	for _, surface := range bodySurfaces {
		if flagutil.FlagChanged(cmd, surface) {
			if err := flagutil.ResolveBodyFlag(cmd, surface); err != nil {
				return err
			}
		}
	}
	suppliedBodyFlag := ""

	if flagutil.FlagChanged(cmd, "body") {
		suppliedBodyFlag = "body"
	}
	bodySupplied := suppliedBodyFlag != ""
	if !bodySupplied {
		attached, err := flagutil.AttachStdinBody(cmd, "body")
		if err != nil {
			return err
		}
		bodySupplied = attached
	}
	if hint := flagutil.SpacedBoolValueHint(cmd, args); hint != "" && !client.IsJSONDryRun(cmd) && !output.IsMachineMode(cmd) {
		fmt.Fprintln(cmd.ErrOrStderr(), hint)
	}
	if bodySupplied {
		if len(args) > 0 {
			if err := flagutil.MergeInputIntoBody(cmd, suppliedBodyFlag, "input", "the <prompt> argument", strings.Join(args, " ")); err != nil {
				return flagutil.WithCLIValidation(err)
			}
		}
		if flagutil.FlagChanged(cmd, "model") {
			v, _ := flagutil.GetStringFlag(cmd, "model")
			if err := flagutil.MergeInputIntoBody(cmd, suppliedBodyFlag, "model", "--model", v); err != nil {
				return flagutil.WithCLIValidation(err)
			}
		}
	}
	if len(args) == 0 && !bodySupplied && !flagutil.FlagChanged(cmd, "body") && !flagutil.FlagChanged(cmd, "model") {
		return output.UsageHelpError(cmd, fmt.Errorf("%s", "missing required argument <prompt> (or pass a full request with --body)"))
	}
	if !bodySupplied {
		body := map[string]any{}
		if err := json.Unmarshal([]byte(intentVideoPreset.Preset), &body); err != nil {
			return err
		}
		if len(args) == 0 {
			return flagutil.WithCLIValidation(fmt.Errorf("missing required argument (or pass a full request with --body)"))
		}
		if len(args) > 0 {
			body["input"] = strings.Join(args, " ")
		}
		if flagutil.FlagChanged(cmd, "model") {
			v, _ := flagutil.GetStringFlag(cmd, "model")
			body["model"] = v
		}
		encoded, err := json.Marshal(body)
		if err != nil {
			return err
		}
		if err := cmd.Flags().Set("body", string(encoded)); err != nil {
			return err
		}
	} else {
		for _, surface := range bodySurfaces {
			if !flagutil.FlagChanged(cmd, surface) {
				continue
			}
			raw, _ := flagutil.GetStringFlag(cmd, surface)
			merged, err := flagutil.MergePresetBody(raw, intentVideoPreset)
			if err != nil {
				return err
			}
			if err := cmd.Flags().Set(surface, merged); err != nil {
				return err
			}
		}
		if suppliedBodyFlag == "" {
			if err := flagutil.MergePresetStdinBody(cmd, intentVideoPreset); err != nil {
				return err
			}
		}
	}
	if err := output.ValidateAsyncFlags(cmd); err != nil {
		return err
	}
	res, err := executeRunCmd(cmd, nil, true)
	if err != nil {
		return err
	}
	if client.IsDryRun(cmd) {
		return nil
	}
	return output.AsyncResult(cmd, res, newPollIntentVideo)
}
func newPollIntentVideo(cmd *cobra.Command, id string, params []output.AsyncParameter) (output.AsyncPollFunc, error) {
	request := &operations.GetInteractionByIDRequest{}
	if err := flagutil.SetRequestParameter(request, "status", "path", "interactionsId", id); err != nil {
		return nil, err
	}
	for _, param := range params {
		if err := flagutil.SetRequestParameter(request, "status", param.In, param.Name, param.Value); err != nil {
			return nil, err
		}
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return nil, err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return nil, err
	}
	sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	return func(ctx context.Context) (interface{}, error) {
		res, err := s.Agent.Status(ctx, *request, sdkOpts...)
		if err != nil {
			return nil, err
		}
		return res, nil
	}, nil
}
