// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agent

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/google-gemini/gemini-api-cli/internal/client"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/interactive"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitIntentGenerate(parent *cobra.Command) error {
	cmd := &cobra.Command{
		Use:     "generate [prompt]",
		Short:   "Text & multimodal generation (gemini-3.6-flash)",
		Long:    "Send a prompt to a Gemini model and print the reply as it is\ngenerated; text deltas are streamed directly to stdout. Uses the\nschema's default model (gemini-3.6-flash) unless --model or a full\n--body names one. --stream=false returns one complete interaction;\n--output-format json shows the raw NDJSON event stream. Thinking\nmodels such as gemini-3.6-flash may emit their deltas in a burst\nafter thinking; gemini-2.5-flash streams visibly. Full request\ncontrol: \"gemini-api agent run\".\n\nArguments:\n  <prompt>  Prompt to send to the model",
		Example: "  gemini-api generate \"Write a haiku about APIs\" --model gemini-2.5-pro\n  gemini-api generate \"Explain concurrency in one sentence\"",
		Args:    cobra.ArbitraryArgs,
		RunE:    runIntentGenerateCmd,
		Annotations: map[string]string{
			"speakeasy_operation":            "CreateInteraction",
			flagutil.AnnotationWholeBodyFlag: "body",
			"speakeasy_strict_body_keys":     "true",
			"speakeasy_help_defaults":        "model gemini-3.6-flash · streams the reply (--stream=false for one result)",
			"speakeasy_help_learn":           "https://ai.google.dev/gemini-api/docs/text-generation",
			"speakeasy_help_escalate":        "full request control via gemini-api agent run",
			"speakeasy_stream_select":        "/data/delta/text",
		},
	}
	flagutil.RegisterFlags(cmd, runCmdMeta)
	flagutil.SetMetaPromptOptional(cmd, runCmdMeta, false)
	flagutil.ClearBodyRequirements(cmd, runCmdMeta, "Body")
	cmd.Flags().String("body", "", "Request body as JSON (advanced; replaces intent arguments). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	if err := flagutil.AnnotateBodyFields(cmd, runCmdMeta, "Body", "body", "body-param"); err != nil {
		return fmt.Errorf("annotate body fields for intent generate: %w", err)
	}
	_ = flagutil.MarkBodyFlag(cmd, "body-param")
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	cmd.Flags().StringP("model", "m", "", "Model to use (see \"gemini-api models\") (e.g. gemini-2.5-flash, gemini-2.5-pro, gemma-4-26b-a4b-it, gemma-4-31b-it, ..., default: gemini-3.6-flash)")
	_ = flagutil.AnnotatePromptFlag(cmd, "model", flagutil.PromptFlagSpec{
		Required: false,
		Kind:     "string",
		Order:    0,
		// A supplied whole body carries this flag's bound key (and the
		// backing operation flag supplies it directly): no prompt then.
		BodySources: []string{"body", "body-param"},
	})
	cmd.Flags().BoolP("stream", "", false, "Stream the reply as it is generated; use --stream=false for a single complete result (default: true)")
	_ = flagutil.AnnotatePromptFlag(cmd, "stream", flagutil.PromptFlagSpec{
		Required: false,
		Kind:     "bool",
		Order:    1,
		// A supplied whole body carries this flag's bound key (and the
		// backing operation flag supplies it directly): no prompt then.
		BodySources: []string{"body", "body-param"},
	})
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{
			Name: "prompt", Summary: "Prompt to send to the model",
			Required: true, Variadic: true,
			BodyKey:     "input",
			SatisfiedBy: []string{"body", "body-param"},
		},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for intent generate: %w", err)
	}
	for _, sibling := range parent.Commands() {
		if sibling.Name() == cmd.Name() || sibling.HasAlias(cmd.Name()) {
			return fmt.Errorf("intent command %q collides with the name or alias of an existing %q command; rename the declared command", "generate", sibling.Name())
		}
	}
	parent.AddCommand(cmd)
	return nil
}

var intentGeneratePreset = flagutil.PresetMerge{
	Command: "generate",
	Variant: "ModelInteraction",
	Preset:  "{\"stream\":true}",
	Foreign: []string{"agent"},
	Escape:  "gemini-api agent run",
}

func runIntentGenerateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "CreateInteraction")
	}
	bodySurfaces := []string{"body", "body-param"}
	for _, surface := range bodySurfaces {
		if flagutil.FlagChanged(cmd, surface) {
			if err := flagutil.ResolveBodyFlag(cmd, surface); err != nil {
				return err
			}
		}
	}
	suppliedBodyFlag := ""
	if flagutil.FlagChanged(cmd, "body-param") {
		suppliedBodyFlag = "body-param"
	}
	if flagutil.FlagChanged(cmd, "body") {
		suppliedBodyFlag = "body"
	}
	bodySupplied := suppliedBodyFlag != ""
	if !bodySupplied {
		attached, err := flagutil.AttachStdinBody(cmd, "body")
		if err != nil {
			return err
		}
		bodySupplied = attached
	}
	if hint := flagutil.SpacedBoolValueHint(cmd, args); hint != "" && !client.IsJSONDryRun(cmd) && !output.IsMachineMode(cmd) {
		fmt.Fprintln(cmd.ErrOrStderr(), hint)
	}
	if bodySupplied {
		if len(args) > 0 {
			if err := flagutil.MergeInputIntoBody(cmd, suppliedBodyFlag, "input", "the <prompt> argument", strings.Join(args, " ")); err != nil {
				return flagutil.WithCLIValidation(err)
			}
		}
		if flagutil.FlagChanged(cmd, "model") {
			v, _ := flagutil.GetStringFlag(cmd, "model")
			if err := flagutil.MergeInputIntoBody(cmd, suppliedBodyFlag, "model", "--model", v); err != nil {
				return flagutil.WithCLIValidation(err)
			}
		}
		if flagutil.FlagChanged(cmd, "stream") {
			v, _ := cmd.Flags().GetBool("stream")
			if err := flagutil.MergeInputIntoBody(cmd, suppliedBodyFlag, "stream", "--stream", v); err != nil {
				return flagutil.WithCLIValidation(err)
			}
		}
	}
	if len(args) == 0 && !bodySupplied && !flagutil.FlagChanged(cmd, "body") && !flagutil.FlagChanged(cmd, "body-param") && !flagutil.FlagChanged(cmd, "model") && !flagutil.FlagChanged(cmd, "stream") {
		return output.UsageHelpError(cmd, fmt.Errorf("%s", "missing required argument <prompt> (or pass a full request with --body)"))
	}
	if !bodySupplied {
		body := map[string]any{}
		if err := json.Unmarshal([]byte(intentGeneratePreset.Preset), &body); err != nil {
			return err
		}
		if len(args) == 0 {
			return flagutil.WithCLIValidation(fmt.Errorf("missing required argument (or pass a full request with --body)"))
		}
		if len(args) > 0 {
			body["input"] = strings.Join(args, " ")
		}
		if flagutil.FlagChanged(cmd, "model") {
			v, _ := flagutil.GetStringFlag(cmd, "model")
			body["model"] = v
		}
		if flagutil.FlagChanged(cmd, "stream") {
			v, _ := cmd.Flags().GetBool("stream")
			body["stream"] = v
		}
		encoded, err := json.Marshal(body)
		if err != nil {
			return err
		}
		if err := cmd.Flags().Set("body", string(encoded)); err != nil {
			return err
		}
	} else {
		for _, surface := range bodySurfaces {
			if !flagutil.FlagChanged(cmd, surface) {
				continue
			}
			raw, _ := flagutil.GetStringFlag(cmd, surface)
			merged, err := flagutil.MergePresetBody(raw, intentGeneratePreset)
			if err != nil {
				return err
			}
			if err := cmd.Flags().Set(surface, merged); err != nil {
				return err
			}
		}
	}
	return runRunCmd(cmd, nil)
}
