// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agent

import (
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitAgentRoot(parent *cobra.Command) error {
	var AgentCmd = &cobra.Command{
		Use:         "agent",
		Short:       "Run interactions with Gemini models or managed agents, and manage agent definitions",
		Long:        "Run interactions with Gemini models or managed agents, and manage agent definitions.\n\nStart here:\n  gemini-api agent run --help\n\nOther common flows:\n  gemini-api agent create --help   Define a managed agent\n  gemini-api agent status --help   Inspect a background interaction\n\nNote: agent IDs and interaction IDs are distinct resources. \"agent status\"\ntakes an interaction ID; to inspect an agent definition use \"agent get\".",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(AgentCmd); err != nil {
		return err
	}

	if err := initCreateCmd(AgentCmd); err != nil {
		return err
	}

	if err := initDeleteInteractionCmd(AgentCmd); err != nil {
		return err
	}

	if err := initStatusCmd(AgentCmd); err != nil {
		return err
	}

	if err := initCancelCmd(AgentCmd); err != nil {
		return err
	}

	parent.AddCommand(AgentCmd)
	return nil
}
