// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agent

import (
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/client"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/operations"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

var runCmdMeta = []flagutil.FlagMeta{
	{FlagName: "body-param", Shorthand: "b", FieldPath: "Body", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, VariantKeys: []string{"agent", "model"}, DefaultJSON: "{\"model\":\"gemini-3.6-flash\"}", TypeDescription: "JSON value (one of: { \"agent\": string, \"stream\": boolean (default: true), ... } | { \"model\": string (default: gemini-3.6-flash), \"stream\": boolean (default: true), ... }; default when neither is named: {\"model\":\"gemini-3.6-flash\"})"}},
}

// initRunCmd initializes the run command.
func initRunCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "run",
		Short:   "Run an interaction with a Gemini model or a managed agent",
		Long:    "Run one interaction with either a Gemini model or an existing managed agent.\nProvide input and choose exactly one selector: \"model\" or \"agent\".\n\nFor a first model run, use gemini-3.6-flash (recommended starting model).\nOther model IDs: https://ai.google.dev/gemini-api/docs/models\n\nPass the full JSON with --body or stdin. Set \"background\": true to\nreturn immediately with an interaction ID, then poll:\n  gemini-api agent status --id <interaction-id>\n\nBy default, streamed responses write the string selected by $.data.delta.text raw as it arrives. Use --stream=false to request one complete JSON response; use -o json to keep each full streamed event.",
		Example: "  gemini-api agent run --body '{\"environment\":\"<value>\",\"generation_config\":{\"tool_choice\":{\"allowed_tools\":{\"mode\":\"any\",\"tools\":[\"my_tool\"]\x7d\x7d},\"input\":\"<value>\",\"model\":\"gemini-3.6-flash\",\"response_format\":{\"0\":{\"type\":\"text\",\"mime_type\":\"application/json\"\x7d\x7d,\"stream\":true}'\n  gemini-api agent run --body '{\"background\":true,\"input\":\"Write a detailed research report on solar batteries\",\"model\":\"gemini-3.6-flash\",\"stream\":true}'\n  gemini-api agent run --body '{\"input\":\"Explain the difference between concurrency and parallelism\",\"model\":\"gemini-3.6-flash\",\"stream\":true}'",
		Args:    cobra.NoArgs,
		RunE:    runRunCmd,
		Annotations: map[string]string{
			"speakeasy_operation":     "CreateInteraction",
			"speakeasy_stream_select": "/data/delta/text",
		},
	}
	flagutil.RegisterFlags(cmd, runCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateInteractionRequest](runCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for run: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, runCmdMeta, "Body", "body"); err != nil {
		return fmt.Errorf("annotate body fields for run: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	cmd.Flags().BoolP("stream", "", true, "Stream the reply as it is generated; use --stream=false for one complete interaction")
	if err := cmd.Flags().SetAnnotation("stream", flagutil.AnnotationOpDeclaredInput, []string{"stream"}); err != nil {
		return err
	}
	_ = flagutil.AnnotatePromptFlag(cmd, "stream", flagutil.PromptFlagSpec{
		PromptOptional:  true,
		Kind:            "bool",
		DefaultResolves: true,
	})
	parent.AddCommand(cmd)
	return nil
}

// runRunCmd executes the run command.
func runRunCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "CreateInteraction")
	}
	if err := flagutil.MergeOperationDeclaredInputs(cmd, []string{
		"body",
		"body-param",
	}, "body-param", true); err != nil {
		return err
	}
	res, err := executeRunCmd(cmd, args, false)
	if err != nil {
		return err
	}
	if res == nil {
		return nil
	}
	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
func executeRunCmd(cmd *cobra.Command, args []string, asyncIntent bool) (*operations.CreateInteractionResponse, error) {
	req, err := flagutil.BuildRequest[operations.CreateInteractionRequest](cmd, runCmdMeta, "Body", "body")
	if err != nil {
		return nil, flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return nil, err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return nil, err
	}
	if client.IsDryRun(cmd) || asyncIntent {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if !client.IsDryRun(cmd) && !asyncIntent {
		res, err := s.Agent.Run(cmd.Context(), *req, sdkOpts...)
		if err != nil {
			return nil, output.Error(cmd, err)
		}
		if err := output.StreamResult(cmd, res, "InteractionSSEStreamEvent"); err != nil {
			return nil, err
		}
		return nil, nil
	}
	if asyncIntent || output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Agent.Run(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return nil, output.Error(cmd, err)
	}
	return res, nil
}
