// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agent

import (
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/client"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/operations"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

var statusCmdMeta = []flagutil.FlagMeta{
	{FlagName: "include-input", FieldPath: "IncludeInput", Kind: flagutil.FlagKindBool, Optional: true, Description: "If true, includes the input in the response."},
	{FlagName: "id", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Required. The name of the interaction to retrieve. [required]"},
	{FlagName: "last-event-id", Shorthand: "l", FieldPath: "LastEventID", Kind: flagutil.FlagKindString, Optional: true, Description: "If set, resumes the interaction stream from the chunk after the event\nmarked by the event id. Can only be used if `stream` is true."},
	{FlagName: "stream", Shorthand: "s", FieldPath: "Stream", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, DefaultBool: true, Description: "Stream the interaction's events (replayed from the start for a finished interaction) instead of returning the status object. Defaults to true; use --stream=false for the status object."},
}

// initStatusCmd initializes the status command.
func initStatusCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "status",
		Short:   "Get status and output of an interaction by interaction ID",
		Long:    "Get the status and output of an interaction by interaction ID. Use this to poll a background run started with \"agent run\".\n\nStreamed responses write the string selected by $.data.delta.text raw as it arrives. Pass --stream to request a streamed response; use -o json to keep each full streamed event.",
		Example: "  gemini-api agent status --id <id>",
		Args:    cobra.NoArgs,
		RunE:    runStatusCmd,
		Annotations: map[string]string{
			"speakeasy_operation":     "getInteractionById",
			"speakeasy_stream_select": "/data/delta/text",
		},
	}
	flagutil.RegisterFlags(cmd, statusCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetInteractionByIDRequest](statusCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for status: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runStatusCmd executes the status command.
func runStatusCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.GetInteractionByIDRequest](cmd, statusCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	// Streaming response — iterate events and output incrementally.
	// Skip streaming iteration in dry-run mode (synthetic response has no stream).
	if !client.IsDryRun(cmd) {
		res, err := s.Agent.Status(cmd.Context(), *req, sdkOpts...)
		if err != nil {
			return output.Error(cmd, err)
		}
		return output.StreamResult(cmd, res, "InteractionSSEStreamEvent")
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Agent.Status(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
