// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package credentials

import (
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/client"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/operations"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

var createCmdMeta = []flagutil.FlagMeta{
	{FlagName: "body-param", Shorthand: "b", FieldPath: "Body", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: true, DiscriminatorKey: "Type", TypeDescription: "JSON value (variants: environment_variable: { \"id\": string, \"injection_location\": string | string[], \"value\": string, ... }, bearer_token: { \"id\": string, \"token\": string, ... }, oauth2: { \"client_id\": string, \"client_secret\": string, \"id\": string, \"refresh_token\": string, ... })", Variants: []flagutil.UnionVariantMeta{
		{DiscriminatorValue: "environment_variable", FlagName: "body-param.environment-variable", FieldName: "EnvironmentVariableConfig", CanExpand: false, Description: "EnvironmentVariableConfig variant as JSON"},
		{DiscriminatorValue: "bearer_token", FlagName: "body-param.bearer-token", FieldName: "HTTPBearerConfig", CanExpand: true, Description: "HttpBearerConfig variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "body-param.bearer-token.header-name", FieldPath: "HeaderName", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional. Header name to inject the token into. Defaults to\n'Authorization'."},
			{FlagName: "body-param.bearer-token.id", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
			{FlagName: "body-param.bearer-token.prefix", FieldPath: "Prefix", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional. Prefix to prepend to the token. Defaults to 'Bearer'. Set to ''\nfor no prefix."},
			{FlagName: "body-param.bearer-token.token", FieldPath: "Token", Kind: flagutil.FlagKindString, Required: true, Description: "Required. Input only. The static bearer token. Write-only; never returned in responses. [required]"},
		}},
		{DiscriminatorValue: "oauth2", FlagName: "body-param.oauth2", FieldName: "OAuth2Config", CanExpand: false, Description: "OAuth2Config variant as JSON"},
	}}},
}

// initCreateCmd initializes the create command.
func initCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Creates a new credential.",
		Long:    "Creates a new credential.",
		Example: "",
		Args:    cobra.NoArgs,
		RunE:    runCreateCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "CreateCredential",
		},
	}
	flagutil.RegisterFlags(cmd, createCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateCredentialRequest](createCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, createCmdMeta, "Body", "body"); err != nil {
		return fmt.Errorf("annotate body fields for create: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runCreateCmd executes the create command.
func runCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "CreateCredential")
	}
	req, err := flagutil.BuildRequest[operations.CreateCredentialRequest](cmd, createCmdMeta, "Body", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Credentials.Create(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
