// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package credentials

import (
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitCredentialsRoot(parent *cobra.Command) error {
	var CredentialsCmd = &cobra.Command{
		Use:         "credentials",
		Short:       "Operations for credentials",
		Long:        "Operations for credentials",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(CredentialsCmd); err != nil {
		return err
	}

	if err := initCreateCmd(CredentialsCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(CredentialsCmd); err != nil {
		return err
	}

	if err := initGetCmd(CredentialsCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(CredentialsCmd); err != nil {
		return err
	}

	parent.AddCommand(CredentialsCmd)
	return nil
}
