// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package voices

import (
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/client"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/operations"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

var listCmdMeta = []flagutil.FlagMeta{
	{FlagName: "accent", Shorthand: "a", FieldPath: "Accent", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Optional. Filter by accent description (e.g. \"American\", \"British\").\nCase-insensitive exact match. If multiple values are specified, matches\nvoices with any of the specified accents (OR)."},
	{FlagName: "contexts", Shorthand: "c", FieldPath: "Contexts", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Optional. Filter by intended context or domain (e.g. \"News, Commercial\").\nCase-insensitive exact match. If multiple values are specified, matches\nvoices with any of the specified contexts (OR)."},
	{FlagName: "gender", Shorthand: "g", FieldPath: "Gender", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Optional. Filter by gender presentation (e.g. \"female\", \"male\", \"neutral\").\nCase-insensitive exact match. If multiple values are specified, matches\nvoices with any of the specified genders (OR)."},
	{FlagName: "language-code", Shorthand: "l", FieldPath: "LanguageCode", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Optional. Filter by BCP-47 language code (e.g. \"en-US\").\nCase-insensitive exact match. If multiple values are specified, matches\nvoices with any of the specified language codes (OR)."},
	{FlagName: "page-size", FieldPath: "PageSize", Kind: flagutil.FlagKindInt64, Optional: true, Description: "Optional. The maximum number of voices to return per page. The service may\nreturn fewer than this value. If unspecified, at most 50 voices are\nreturned. The maximum value is 1000; values above 1000 are coerced to\n1000."},
	{FlagName: "page-token", FieldPath: "PageToken", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional. A page token received from a previous `ListVoices` call. Provide\nthis to retrieve the subsequent page.\n\nWhen paginating, all filter query parameters (`language_code`,\n`region_code`, `accent`, `persona`, `context`, `gender`, `pitch`, `type`,\nand `search`) must match the call that returned this token; otherwise the\nrequest fails with `INVALID_ARGUMENT`. `page_size` may change between\npages."},
	{FlagName: "persona", FieldPath: "Persona", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Optional. Filter by vocal persona (e.g. \"Warm, Friendly\").\nCase-insensitive exact match. If multiple values are specified, matches\nvoices with any of the specified personas (OR)."},
	{FlagName: "pitch", FieldPath: "Pitch", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Optional. Filter by vocal pitch. Accepts \"low\", \"medium\", \"high\" or\n\"PITCH_LOW\", \"PITCH_MEDIUM\", \"PITCH_HIGH\" (case-insensitive). If multiple\nvalues are specified, matches voices with any of the specified pitches\n(OR)."},
	{FlagName: "region-code", Shorthand: "r", FieldPath: "RegionCode", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Optional. Filter by ISO 3166-1 alpha-2 or UN M.49 region code (e.g. \"US\",\n\"001\").\nCase-insensitive exact match. If multiple values are specified, matches\nvoices with any of the specified region codes (OR)."},
	{FlagName: "search", Shorthand: "s", FieldPath: "Search", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional. Free-text substring search query matched case-insensitively\nagainst both `display_name` and `description`. Maximum 2048 bytes."},
	{FlagName: "type", Shorthand: "t", FieldPath: "Type", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Optional. Filter by voice type. Accepts \"prebuilt\", \"replicated\",\n\"prompted\" or \"VOICE_TYPE_PREBUILT\", \"VOICE_TYPE_REPLICATED\",\n\"VOICE_TYPE_PROMPTED\" (case-insensitive). If multiple values are specified,\nmatches voices with any of the specified types (OR)."},
}

// initListCmd initializes the list command.
func initListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "Lists custom stored voices owned by the caller (ordered newest first)\nfollowed by prebuilt system voices from Google's voice catalog.",
		Long:    "Lists custom stored voices owned by the caller (ordered newest first)\nfollowed by prebuilt system voices from Google's voice catalog.",
		Example: "  gemini-api voices list",
		Args:    cobra.NoArgs,
		RunE:    runListCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "ListVoices",
		},
	}
	flagutil.RegisterFlags(cmd, listCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListVoicesRequest](listCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListCmd executes the list command.
func runListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.ListVoicesRequest](cmd, listCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Voices.List(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
