// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package main

import (
	"errors"
	"fmt"
	"os"

	"github.com/google-gemini/gemini-api-cli/internal/cli"
	"github.com/google-gemini/gemini-api-cli/internal/clierrors"
)

// version and buildTime can be set at build time using Go linker flags:
//
//	go build -ldflags "-X main.version=x.y.z -X main.buildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)" ./cmd/gemini-api
var version string
var buildTime string

func main() {
	if version != "" {
		cli.Version = version
	}
	if buildTime != "" {
		cli.BuildTime = buildTime
	}

	if err := cli.Execute(); err != nil {
		var rendered interface{ Rendered() bool }
		if !errors.As(err, &rendered) || !rendered.Rendered() {
			fmt.Fprintln(os.Stderr, err)
		}
		os.Exit(clierrors.ExitCode(err))
	}
}
