// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package models

import (
	"fmt"

	"github.com/google-gemini/gemini-api-cli/internal/client"
	"github.com/google-gemini/gemini-api-cli/internal/flagutil"
	"github.com/google-gemini/gemini-api-cli/internal/output"
	"github.com/google-gemini/gemini-api-cli/internal/sdk/models/operations"
	"github.com/google-gemini/gemini-api-cli/internal/usage"
	"github.com/spf13/cobra"
)

var modelsListCmdMeta = []flagutil.FlagMeta{
	{FlagName: "page-size", FieldPath: "PageSize", Kind: flagutil.FlagKindInt64, Optional: true, Description: "Maximum number of models to return per page (default 50, maximum 1000)"},
	{FlagName: "page-token", FieldPath: "PageToken", Kind: flagutil.FlagKindString, Optional: true, Description: "Page token from a previous models list call"},
}

// initModelsListCmd initializes the models-list command.
func initModelsListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List the models the API serves (live; bare \"models\" is the offline catalog)",
		Long:    "Lists the models available through the Gemini API. See https://ai.google.dev/gemini-api/docs/models",
		Example: "  gemini-api models list",
		Args:    cobra.NoArgs,
		RunE:    runModelsListCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "ModelsList",
		},
	}
	flagutil.RegisterFlags(cmd, modelsListCmdMeta)
	if err := flagutil.ValidateMeta[operations.ModelsListRequest](modelsListCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for models-list: %w", err)
	}
	cmd.Flags().BoolP("all", "a", false, "Automatically paginate and fetch all results (streams NDJSON for JSON output)")
	cmd.Flags().Int("max-pages", 0, "Maximum number of pages to fetch when using --all (0 = no limit)")
	parent.AddCommand(cmd)
	return nil
}

// runModelsListCmd executes the models-list command.
func runModelsListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	allPages, _ := flagutil.GetBoolFlag(cmd, "all")
	maxPages, _ := flagutil.GetIntFlag(cmd, "max-pages")
	if maxPages < 0 {
		return flagutil.WithCLIValidation(fmt.Errorf("--max-pages must be zero or greater"))
	}
	if flagutil.FlagChanged(cmd, "max-pages") && !allPages {
		return flagutil.WithCLIValidation(fmt.Errorf("--max-pages requires --all"))
	}
	req, err := flagutil.BuildRequest[operations.ModelsListRequest](cmd, modelsListCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if allPages && !client.IsDryRun(cmd) {
		res, err := s.Models.ModelsList(cmd.Context(), req, sdkOpts...)
		if err != nil {
			return output.Error(cmd, err)
		}
		return output.PaginatedResult(cmd, res, "ListModelsResponse", "", maxPages, output.PaginationProbe{
			Type:       "cursor",
			CursorKind: "string",
			NextCursor: "$.nextPageToken",
			NextURL:    "",
			Results:    "",
			HasLimit:   false,
		})
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Models.ModelsList(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}
	morePages := output.HasMorePages(res, output.PaginationProbe{
		Type:       "cursor",
		CursorKind: "string",
		NextCursor: "$.nextPageToken",
		NextURL:    "",
		Results:    "",
		HasLimit:   false,
	})

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	if morePages && !client.IsDryRun(cmd) && !output.IsMachineMode(cmd) {
		fmt.Fprintln(cmd.ErrOrStderr(), "Hint: more pages available. Use --all to fetch all results, or --page-token for manual pagination.")
	}
	return nil
}
